/*
 * App URI: PosAccountSearch
 * Source Location: PosAccountSearch.clx
 *
 * This file was generated by eXBuilder6 compiler(1.0.4878), Don't edit manually.
 */
(function() {
	var app = new cpr.core.App("PosAccountSearch", { 
		onPrepare: function(loader) {
		},
		onCreate: function(/* cpr.core.AppInstance */ app, exports) {
			var linker = {};
			// Start - User Script
			/************************************************
			 * PosAccountSearch.js
			 * Created at 2024. 2. 27. 오후 1:22:28.
			 *
			 * @author sunrise
			 ************************************************/;
			// End - User Script
			
			// Header
			app.supportMedia("all and (min-width: 1024px)", "default");
			app.supportMedia("all and (min-width: 500px) and (max-width: 1023px)", "tablet");
			app.supportMedia("all and (max-width: 499px)", "mobile");
			
			// Configure root container
			var container = app.getContainer();
			container.style.css({
				"width" : "100%",
				"height" : "100%"
			});
			
			// Layout
			var xYLayout_1 = new cpr.controls.layouts.XYLayout();
			container.setLayout(xYLayout_1);
			
			// UI Configuration
			var embeddedApp_1 = new cpr.controls.EmbeddedApp("ea1");
			cpr.core.App.load("PosHeader", function(app) {
				if(app){
					embeddedApp_1.app = app;
				}
			});
			container.addChild(embeddedApp_1, {
				"top": "0px",
				"left": "0px",
				"width": "1024px",
				"height": "80px"
			});
			
			var output_1 = new cpr.controls.Output();
			output_1.value = "구현중";
			output_1.style.css({
				"font-weight" : "bolder",
				"font-size" : "20px",
				"text-align" : "center"
			});
			container.addChild(output_1, {
				"top": "200px",
				"left": "314px",
				"width": "396px",
				"height": "125px"
			});
		}
	});
	app.title = "PosAccountSearch";
	cpr.core.Platform.INSTANCE.register(app);
})();
