/*
 * App URI: PosCust
 * Source Location: PosCust.clx
 *
 * This file was generated by eXBuilder6 compiler(1.0.4878), Don't edit manually.
 */
(function() {
	var app = new cpr.core.App("PosCust", { 
		onPrepare: function(loader) {
			loader.addScript("js/daumApi.js");
		},
		onCreate: function(/* cpr.core.AppInstance */ app, exports) {
			var linker = {};
			// Start - User Script
			/************************************************
			 * PosCust.js
			 * Created at 2024. 1. 22. 오전 1:13:47.
			 *
			 * @author PC2
			 ************************************************/

			/*
			 * 루트 컨테이너에서 load 이벤트 발생 시 호출.
			 * 앱이 최초 구성된후 최초 랜더링 직후에 발생하는 이벤트 입니다.
			 */
			function onBodyLoad(/* cpr.events.CUIEvent */e){
				
				// daumApi 스크립트 억지로 집어넣어주는 코드
				var scriptElement = document.createElement("script");
				var daumApi = "t1.daumcdn.net/mapjsapi/bundle/postcode/prod/postcode.v2.js";
				scriptElement.src = "http://" + daumApi;
				document.body.appendChild(scriptElement);
				
			//	var utilProperty = cpr.core.Module.require("ui/js/daumApi.module.js");
			//	var utilProperty = cpr.core.Module.require("module/js/daumApi.module.js");
			//	console.log(utilProperty);
			//	var svg = app.lookup("custForm");
			//  	var xmlns = "http://dmaps.daum.net/map_js_init/postcode.v2.js";
			//  	var svgElem = document.createElementNS(xmlns, "svg");
			//  	
			//  	svgElem.setAttributeNS(null, "width", "400px");
			//  	svgElem.setAttributeNS(null, "hight", "600px");
			//  	svgElem.setAttributeNS(null, "popup", "popup");
				
				var submission = new cpr.protocols.Submission();
				submission.action = '/POS/memberPageInit.do';
				submission.responseType = 'javascript';
				submission.addEventListener("receive", function(e){
					var jsonObj = JSON.parse(e.control.xhr.responseText);
					app.lookup("MEMB_SER_NO").value = jsonObj['memCnt'];
				});
				submission.send();
				
			  	app.lookup("PERS_COP_TY").selectItem(0);
			  	
			}

			/*
			 * "등 록" 버튼에서 click 이벤트 발생 시 호출.
			 * 사용자가 컨트롤을 클릭할 때 발생하는 이벤트.
			 */
			function onButtonClick(e){
				var button = e.control;
				
				
				if(chkDupl()){
					debugger;
					var idNo = app.lookup("ID_NO");
					var busiNo = app.lookup("BUSI_NO");
					var membNm = app.lookup("MEMB_NM");
					var membEngNm = app.lookup("MEMB_ENG_NM");
					var birDay = app.lookup("BIR_DAY");
					var mobPhNo = app.lookup("MOB_PH_NO");
					var phNo = app.lookup("PH_NO");
					var email = app.lookup("EMAIL");
					var persCopTy = app.lookup("PERS_COP_TY");
					var postNo = app.lookup("POST_NO");
					var addr1 = app.lookup("ADDR_1");
					var addr2 = app.lookup("ADDR_2");
					console.log(persCopTy.value);
					var submission = new cpr.protocols.Submission();
					submission.action = '/POS/addMember.do';
					submission.responseType = 'text';
			//		submission.async = false;
					submission.setParameters("ID_NO", idNo.value);
					submission.setParameters("BUSI_NO", busiNo.value);
					submission.setParameters("MEMB_NM", membNm.value);
					submission.setParameters("MEMB_ENG_NM", membEngNm.value);
					submission.setParameters("BIR_DAY", birDay.value);
					submission.setParameters("MOB_PH_NO", mobPhNo.value);
					submission.setParameters("PH_NO", phNo.value);
					submission.setParameters("EMAIL", email.value);
					submission.setParameters("PERS_COP_TY", persCopTy.value);
					submission.setParameters("POST_NO", postNo.value);
					submission.setParameters("ADDR_1", addr1.value);
					submission.setParameters("ADDR_2", addr2.value);
					submission.addEventListener("submit-success", function(e){
						alert('회원등록이 완료됐습니다.');
					});
					submission.addEventListener("submit-error", function(e){
						alert('회원등록이 실패했습니다.');
					});
					submission.send();
					
				}
				
				
			}

			// 등록전 체크 함수
			function chkDupl(){
				var idNo = app.lookup("ID_NO");
				var busiNo = app.lookup("BUSI_NO");
				var membNm = app.lookup("MEMB_NM");
				var membEngNm = app.lookup("MEMB_ENG_NM");
				var birDay = app.lookup("BIR_DAY");
				var mobPhNo = app.lookup("MOB_PH_NO");
				var phNo = app.lookup("PH_NO");
				var email = app.lookup("EMAIL");
				var persCopTy = app.lookup("PERS_COP_TY");
				var postNo = app.lookup("POST_NO");
				var addr1 = app.lookup("ADDR_1");
				var addr2 = app.lookup("ADDR_2");
				
				// 현재날짜 계산
				var date = new Date();
				var year = date.getFullYear();
				var mon = date.getMonth() + 1;
				mon = mon.toString().length === 1 ? "0" + mon : mon;
				var day = date.getDate();
				day = day.toString().length === 1 ? "0" + day : day;
				
				var now = year + mon + day;
				
				if(persCopTy.value == 1){
					if(idNo.value == ''){
						alert('주민등록번호를 입력해 주세요.');
						idNo.focus();
						return false;
					
					}else if(idNo.length != 13 && idNo.length > 0){
						alert('주민등록번호가 올바르지 않습니다.');
						idNo.focus();
						return false;
					}
				}
				if(persCopTy.value == 2){
					if(busiNo.value == ''){
						alert('사업자 번호를 입력해 주세요.');
						busiNo.focus();
						return false;
					
					}else if(busiNo.length != 10 && busiNo.length > 0){
						alert('사업자 번호가 올바르지 않습니다.');
						busiNo.focus();
						return false;
					}else if(busiNo.value.substr(0, 3) === '325' && busiNo.length > 0){
						alert('유효하지 않은 사업자 번호입니다.');
						busiNo.focus();
						return false;
					}
				}
				var hgMemTest = /^[가-힣]+$/;
				if(membNm.value == ''){
					alert('회원명을 입력해 주세요.');
					membNm.focus();
					return false;
				}
				if(!hgMemTest.test(membNm.value) && membNm.length > 0){
					alert('유효하지 않은 이름입니다.');
					membNm.focus();
					return false;
				}
				var engMemTest = /(\s)\1/;
				var engMemTest2 = /([,-])\1/;
				var engMemTest3 = /^[a-zA-Z0-9 ,-]+$/;
				if(membEngNm.value == '' && membEngNm.length > 0){
					alert('영문명을 입력해 주세요.');
					membEngNm.focus();
					return false;
				}
				if(engMemTest.test(membEngNm.value)){
					alert('연속된 공백은 불가합니다.');
					membEngNm.focus();
					return false;
				}else if(engMemTest2.test(membEngNm.value) && membEngNm.length > 0){
					alert('연속된 특수문자는 불가합니다.');
					membEngNm.focus();
					return false;
				}else if(!engMemTest3.test(membEngNm.value) && membEngNm.length > 0){
					alert('사용 가능한 특수문자는 다음과 같습니다.( , - )');
					membEngNm.focus();
					return false;
				}
				// 추후 구현할 때 주민등록번호에서 뒷자리 시작이 1,2 일경우 생년월일에 '19'
				// 뒷자리 시작이 3,4 로 시작할 경우에 '20'으로 설정해서 자동으로 계산해주기
				// 계산을 한다면 주민번호 or 생년월일이 바뀌었을 때 값의 셋팅 & 값이 비워졌을때는 어떻게 할껀지?
				if(birDay.value == ''){
					alert('생년월일을 입력해 주세요.');
					birDay.focus();
					return false;
				
				}
				else if(birDay.value > now){
					alert('생년월일이 올바르지 않습니다.');
					birDay.focus();
					return false;
				}
				// 12살 미만일 때
				else if((year - birDay.value.substr(0,4)) < 13){
					alert('만 13세 이상 가입이 가능합니다.');
					birDay.focus();
					return false;
				}
				var mobPhTest = /^01([0|1|6|7|8|9]{1})([0-9]{3,4})([0-9]{4})$/;
				if(mobPhNo.value == ''){
					alert('휴대폰번호를 입력해 주세요.');
					mobPhNo.focus();
					return false;
				}else if(!mobPhTest.test(mobPhNo.value) && mobPhNo.length > 0){
					alert('휴대폰번호가 올바르지 않습니다.');
					mobPhNo.focus();
					return false;
				}
				var phNoTest = /^0\d{1,2}\d{3,4}\d{4}$/;
				if(phNo.length < 9 && phNo.length > 0){
					alert('전화번호가 올바르지 않습니다.');
					phNo.focus();
					return false;
				}else if(phNoTest.test(phNo.value) && phNo.length > 0){
					alert('전화번호가 올바르지 않습니다.');
					phNo.focus();
					return false;
				}
				var emailTest = /^([A-z0-9_\.-]+)@([\da-z\.-]+)\.([a-z\.]{2,3})$/;
			//	if(email.value == ''){
			//		alert('이메일을 작성해 주세요');
			//		email.focus();
			//		return false;
			//	}
				if(emailTest.test(email.value)){
					alert('이메일을 형식이 올바르지 않습니다.');
					email.focus();
					return false;
				}
				if(postNo.value != ''){
					if(addr2.value == ''){
						alert('상세주소를 입력해 주세요.');
						addr2.focus();
						return false;
					}
				}
				if(postNo.value == ''){
					if(addr2.length > 0){
						alert('우편번호를 입력해 주세요.');
						return false;
					}
				}
				return true;
			}

			/*
			 * 라디오 버튼에서 selection-change 이벤트 발생 시 호출.
			 * 라디오버튼 아이템을 선택하여 선택된 값이 저장된 후에 발생하는 이벤트.
			 */
			function onPERS_COP_TYSelectionChange(e){
				var pERS_COP_TY = e.control;
				
				var idNo = app.lookup("ID_NO");
				var busiNo = app.lookup("BUSI_NO");
				var pers = app.lookup("PERS_COP_TY");
				var idNoBox = app.lookup("idNoBox");
				var busiNoBox = app.lookup("busiNoBox");
				if(pers.value == 1){
					busiNo.value = '';
					busiNo.readOnly = true;
					busiNo.placeholder = ''
					idNo.placeholder = '숫자만 입력해 주세요.';
					idNo.readOnly = false;
					idNoBox.visible = true;
					busiNoBox.visible = false;
				}else{
					idNo.value = '';
					idNo.readOnly = true;
					idNo.placeholder = ''
					busiNo.placeholder = '숫자만 입력해 주세요.';
					busiNo.readOnly = false;
					busiNoBox.visible = true;
					idNoBox.visible = false;
				}
			}

			/*
			 * "주소 찾기" 버튼에서 click 이벤트 발생 시 호출.
			 * 사용자가 컨트롤을 클릭할 때 발생하는 이벤트.
			 */
			function onButtonClick2(e){
				postCode();
			}

			function postCode() {
				new daum.Postcode({
					/* 해당 정보를 받아 처리할 콜백 함수를 정의하는 부분 입니다. */
					oncomplete: function(data) {
						/* 팝업에서 검색결과 항목을 클릭했을떄 실행할 코드를 작성하는 부분 */
						var vcPostCode = app.lookup("POST_NO");
						var vcAddress = app.lookup("ADDR_1");
			//			var vcAddressJibun = app.lookup("ADDR_1");
						var vcDetailAddress = app.lookup("ADDR_2");
						var vcExtraAddress = app.lookup("ADDR_2");
						
						// 도로명 주소의 노출 규칙에 따라 주소를 표시한다.
						// 내려오는 변수가 값이 없는 경우엔 공백('')값을 가지므로, 이를 참고하여 분기 한다.
						var roadAddr = data.roadAddress; // 도로명 주소 변수
						var extraRoadAddr = ""; // 참고 항목 변수
						
						// 법정동명이 있을 경우 추가한다. (법정리는 제외)
						// 법정동의 경우 마지막 문자가 "동/로/가"로 끝난다.
						if (data.bname !== "" && /[동|로|가]$/g.test(data.bname)) {
							extraRoadAddr += data.bname;
						}
						// 건물명이 있고, 공동주택일 경우 추가한다.
						if (data.buildingName !== "" && data.apartment === "Y") {
							extraRoadAddr += (extraRoadAddr !== "" ? ", " + data.buildingName : data.buildingName);
						}
						// 표시할 참고항목이 있을 경우, 괄호까지 추가한 최종 문자열을 만든다.
						if (extraRoadAddr !== "") {
							extraRoadAddr = " (" + extraRoadAddr + ")";
						}
						debugger
						// 참고항목 문자열이 있을 경우 해당 필드에 넣는다.
						if (roadAddr !== "") {
							roadAddr += extraRoadAddr;
						} else {
							vcExtraAddress.value = "";
						}
						
						// 우편번호와 주소 정보를 해당 필드에 넣는다.
						vcPostCode.value = data.zonecode;
						vcAddress.value = roadAddr;
			//			vcAddressJibun.value = data.jibunAddress;
						
						/*커서를 상세주소 필드로 이동합니다. */
						vcDetailAddress.focus();
					}
				}).open();
			};
			// End - User Script
			
			// Header
			var dataSet_1 = new cpr.data.DataSet("accountBtn");
			dataSet_1.parseData({
				"columns": [
					{"name": "person"},
					{"name": "value"}
				],
				"rows": [
					{"person": "개인", "value": "1"},
					{"person": "법인", "value": "2"}
				]
			});
			app.register(dataSet_1);
			app.supportMedia("all", "default");
			
			// Configure root container
			var container = app.getContainer();
			container.style.css({
				"width" : "100%",
				"height" : "100%"
			});
			
			// Layout
			var xYLayout_1 = new cpr.controls.layouts.XYLayout();
			container.setLayout(xYLayout_1);
			
			// UI Configuration
			var embeddedApp_1 = new cpr.controls.EmbeddedApp("ea1");
			cpr.core.App.load("PosHeader", function(app) {
				if(app){
					embeddedApp_1.app = app;
				}
			});
			container.addChild(embeddedApp_1, {
				"top": "0px",
				"left": "0px",
				"width": "1024px",
				"height": "80px"
			});
			
			var group_1 = new cpr.controls.Container("custForm");
			group_1.style.css({
				"background-color" : "#E0E0E0",
				"border-radius" : "3px 0px 0px 3px"
			});
			var xYLayout_2 = new cpr.controls.layouts.XYLayout();
			group_1.setLayout(xYLayout_2);
			(function(container){
				var output_1 = new cpr.controls.Output();
				output_1.value = "회원번호";
				output_1.style.css({
					"border-right-style" : "solid",
					"border-bottom-color" : "#cecece",
					"border-top-width" : "1px",
					"border-right-width" : "1px",
					"border-left-color" : "#cecece",
					"border-right-color" : "#cecece",
					"border-left-width" : "1px",
					"border-top-style" : "solid",
					"border-radius" : "5px 0px 0px 5px",
					"background-color" : "#EDEDED",
					"border-left-style" : "solid",
					"border-bottom-width" : "1px",
					"border-top-color" : "#cecece",
					"border-bottom-style" : "solid",
					"text-align" : "center"
				});
				container.addChild(output_1, {
					"top": "110px",
					"left": "50px",
					"width": "100px",
					"height": "35px"
				});
				var inputBox_1 = new cpr.controls.InputBox("MEMB_SER_NO");
				inputBox_1.enabled = false;
				inputBox_1.readOnly = true;
				inputBox_1.style.css({
					"border-radius" : "0px 5px 5px 0px",
					"background-color" : "white",
					"color" : "black",
					"font-weight" : "bolder",
					"font-size" : "16px",
					"text-align" : "center"
				});
				container.addChild(inputBox_1, {
					"top": "110px",
					"left": "149px",
					"width": "170px",
					"height": "35px"
				});
				var output_2 = new cpr.controls.Output();
				output_2.value = "주민번호";
				output_2.style.css({
					"border-right-style" : "solid",
					"border-bottom-color" : "#cecece",
					"border-top-width" : "1px",
					"border-right-width" : "1px",
					"border-left-color" : "#cecece",
					"border-right-color" : "#cecece",
					"border-left-width" : "1px",
					"border-top-style" : "solid",
					"border-radius" : "5px 0px 0px 5px",
					"background-color" : "#EDEDED",
					"border-left-style" : "solid",
					"border-bottom-width" : "1px",
					"border-top-color" : "#cecece",
					"border-bottom-style" : "solid",
					"text-align" : "center"
				});
				container.addChild(output_2, {
					"top": "210px",
					"left": "50px",
					"width": "95px",
					"height": "35px"
				});
				var inputBox_2 = new cpr.controls.InputBox("ID_NO");
				inputBox_2.placeholder = "숫자만 입력해 주세요";
				inputBox_2.maxLength = 13;
				inputBox_2.inputFilter = "[0-9]";
				inputBox_2.style.css({
					"border-radius" : "0px 5px 5px 0px",
					"text-align" : "center"
				});
				container.addChild(inputBox_2, {
					"top": "210px",
					"left": "144px",
					"width": "160px",
					"height": "35px"
				});
				var output_3 = new cpr.controls.Output();
				output_3.value = "사업자 번호";
				output_3.style.css({
					"border-right-style" : "solid",
					"border-bottom-color" : "#cecece",
					"border-top-width" : "1px",
					"border-right-width" : "1px",
					"border-left-color" : "#cecece",
					"border-right-color" : "#cecece",
					"border-left-width" : "1px",
					"border-top-style" : "solid",
					"border-radius" : "5px 0px 0px 5px",
					"background-color" : "#EDEDED",
					"border-left-style" : "solid",
					"border-bottom-width" : "1px",
					"border-top-color" : "#cecece",
					"border-bottom-style" : "solid",
					"text-align" : "center"
				});
				container.addChild(output_3, {
					"top": "270px",
					"left": "50px",
					"width": "95px",
					"height": "35px"
				});
				var inputBox_3 = new cpr.controls.InputBox("BUSI_NO");
				inputBox_3.placeholder = "숫자만 입력해 주세요";
				inputBox_3.maxLength = 10;
				inputBox_3.inputFilter = "[0-9]";
				inputBox_3.style.css({
					"border-radius" : "0px 5px 5px 0px",
					"text-align" : "center"
				});
				container.addChild(inputBox_3, {
					"top": "270px",
					"left": "144px",
					"width": "160px",
					"height": "35px"
				});
				var output_4 = new cpr.controls.Output();
				output_4.value = "회원명";
				output_4.style.css({
					"border-right-style" : "solid",
					"border-bottom-color" : "#cecece",
					"border-top-width" : "1px",
					"border-right-width" : "1px",
					"border-left-color" : "#cecece",
					"border-right-color" : "#cecece",
					"border-left-width" : "1px",
					"border-top-style" : "solid",
					"border-radius" : "5px 0px 0px 5px",
					"background-color" : "#EDEDED",
					"border-left-style" : "solid",
					"border-bottom-width" : "1px",
					"border-top-color" : "#cecece",
					"border-bottom-style" : "solid",
					"text-align" : "center"
				});
				container.addChild(output_4, {
					"top": "330px",
					"left": "50px",
					"width": "95px",
					"height": "35px"
				});
				var inputBox_4 = new cpr.controls.InputBox("MEMB_NM");
				inputBox_4.maxLength = 13;
				inputBox_4.inputFilter = "[ㄱ-힣]";
				inputBox_4.style.css({
					"border-radius" : "0px 5px 5px 0px",
					"text-align" : "center"
				});
				container.addChild(inputBox_4, {
					"top": "330px",
					"left": "144px",
					"width": "160px",
					"height": "35px"
				});
				var output_5 = new cpr.controls.Output();
				output_5.value = "영문명";
				output_5.style.css({
					"border-right-style" : "solid",
					"border-bottom-color" : "#cecece",
					"border-top-width" : "1px",
					"border-right-width" : "1px",
					"border-left-color" : "#cecece",
					"border-right-color" : "#cecece",
					"border-left-width" : "1px",
					"border-top-style" : "solid",
					"border-radius" : "5px 0px 0px 5px",
					"background-color" : "#EDEDED",
					"border-left-style" : "solid",
					"border-bottom-width" : "1px",
					"border-top-color" : "#cecece",
					"border-bottom-style" : "solid",
					"text-align" : "center"
				});
				container.addChild(output_5, {
					"top": "390px",
					"left": "50px",
					"width": "95px",
					"height": "35px"
				});
				var inputBox_5 = new cpr.controls.InputBox("MEMB_ENG_NM");
				inputBox_5.maxLength = 30;
				inputBox_5.inputFilter = "[A-z\\s-,]";
				inputBox_5.style.css({
					"border-radius" : "0px 5px 5px 0px",
					"text-align" : "center"
				});
				container.addChild(inputBox_5, {
					"top": "390px",
					"left": "144px",
					"width": "160px",
					"height": "35px"
				});
				var output_6 = new cpr.controls.Output();
				output_6.value = "생년월일";
				output_6.style.css({
					"border-right-style" : "solid",
					"border-bottom-color" : "#cecece",
					"border-top-width" : "1px",
					"border-right-width" : "1px",
					"border-left-color" : "#cecece",
					"border-right-color" : "#cecece",
					"border-left-width" : "1px",
					"border-top-style" : "solid",
					"border-radius" : "5px 0px 0px 5px",
					"background-color" : "#EDEDED",
					"border-left-style" : "solid",
					"border-bottom-width" : "1px",
					"border-top-color" : "#cecece",
					"border-bottom-style" : "solid",
					"text-align" : "center"
				});
				container.addChild(output_6, {
					"top": "210px",
					"left": "344px",
					"width": "95px",
					"height": "35px"
				});
				var output_7 = new cpr.controls.Output();
				output_7.value = "핸드폰 번호";
				output_7.style.css({
					"border-right-style" : "solid",
					"border-bottom-color" : "#cecece",
					"border-top-width" : "1px",
					"border-right-width" : "1px",
					"border-left-color" : "#cecece",
					"border-right-color" : "#cecece",
					"border-left-width" : "1px",
					"border-top-style" : "solid",
					"border-radius" : "5px 0px 0px 5px",
					"background-color" : "#EDEDED",
					"border-left-style" : "solid",
					"border-bottom-width" : "1px",
					"border-top-color" : "#cecece",
					"border-bottom-style" : "solid",
					"text-align" : "center"
				});
				container.addChild(output_7, {
					"top": "270px",
					"left": "344px",
					"width": "95px",
					"height": "35px"
				});
				var inputBox_6 = new cpr.controls.InputBox("MOB_PH_NO");
				inputBox_6.placeholder = "숫자만 입력해 주세요";
				inputBox_6.maxLength = 12;
				inputBox_6.inputFilter = "[0-9]";
				inputBox_6.style.css({
					"border-radius" : "0px 5px 5px 0px",
					"text-align" : "center"
				});
				container.addChild(inputBox_6, {
					"top": "270px",
					"left": "438px",
					"width": "160px",
					"height": "35px"
				});
				var output_8 = new cpr.controls.Output();
				output_8.value = "전화번호";
				output_8.style.css({
					"border-right-style" : "solid",
					"border-bottom-color" : "#cecece",
					"border-top-width" : "1px",
					"border-right-width" : "1px",
					"border-left-color" : "#cecece",
					"border-right-color" : "#cecece",
					"border-left-width" : "1px",
					"border-top-style" : "solid",
					"border-radius" : "5px 0px 0px 5px",
					"background-color" : "#EDEDED",
					"border-left-style" : "solid",
					"border-bottom-width" : "1px",
					"border-top-color" : "#cecece",
					"border-bottom-style" : "solid",
					"text-align" : "center"
				});
				container.addChild(output_8, {
					"top": "330px",
					"left": "344px",
					"width": "95px",
					"height": "35px"
				});
				var inputBox_7 = new cpr.controls.InputBox("PH_NO");
				inputBox_7.placeholder = "숫자만 입력해 주세요";
				inputBox_7.maxLength = 12;
				inputBox_7.inputFilter = "[0-9]";
				inputBox_7.style.css({
					"border-radius" : "0px 5px 5px 0px",
					"text-align" : "center"
				});
				container.addChild(inputBox_7, {
					"top": "330px",
					"left": "438px",
					"width": "160px",
					"height": "35px"
				});
				var output_9 = new cpr.controls.Output();
				output_9.value = "이메일 주소";
				output_9.style.css({
					"border-right-style" : "solid",
					"border-bottom-color" : "#cecece",
					"border-top-width" : "1px",
					"border-right-width" : "1px",
					"border-left-color" : "#cecece",
					"border-right-color" : "#cecece",
					"border-left-width" : "1px",
					"border-top-style" : "solid",
					"border-radius" : "5px 0px 0px 5px",
					"background-color" : "#EDEDED",
					"border-left-style" : "solid",
					"border-bottom-width" : "1px",
					"border-top-color" : "#cecece",
					"border-bottom-style" : "solid",
					"text-align" : "center"
				});
				container.addChild(output_9, {
					"top": "390px",
					"left": "344px",
					"width": "95px",
					"height": "35px"
				});
				var inputBox_8 = new cpr.controls.InputBox("EMAIL");
				inputBox_8.maxLength = 30;
				inputBox_8.inputFilter = "[0-9A-z\\@.]";
				inputBox_8.style.css({
					"border-radius" : "0px 5px 5px 0px",
					"text-align" : "center"
				});
				container.addChild(inputBox_8, {
					"top": "390px",
					"left": "438px",
					"width": "160px",
					"height": "35px"
				});
				var output_10 = new cpr.controls.Output();
				output_10.value = "회원구분";
				output_10.style.css({
					"border-right-style" : "solid",
					"border-bottom-color" : "#cecece",
					"border-top-width" : "1px",
					"border-right-width" : "1px",
					"border-left-color" : "#cecece",
					"border-right-color" : "#cecece",
					"border-left-width" : "1px",
					"border-top-style" : "solid",
					"border-radius" : "5px 0px 0px 5px",
					"background-color" : "#EDEDED",
					"border-left-style" : "solid",
					"border-bottom-width" : "1px",
					"border-top-color" : "#cecece",
					"border-bottom-style" : "solid",
					"text-align" : "center"
				});
				container.addChild(output_10, {
					"top": "210px",
					"left": "641px",
					"width": "95px",
					"height": "35px"
				});
				var output_11 = new cpr.controls.Output();
				output_11.value = "우편번호";
				output_11.style.css({
					"border-right-style" : "solid",
					"border-bottom-color" : "#cecece",
					"border-top-width" : "1px",
					"border-right-width" : "1px",
					"border-left-color" : "#cecece",
					"border-right-color" : "#cecece",
					"border-left-width" : "1px",
					"border-top-style" : "solid",
					"border-radius" : "5px 0px 0px 5px",
					"background-color" : "#EDEDED",
					"border-left-style" : "solid",
					"border-bottom-width" : "1px",
					"border-top-color" : "#cecece",
					"border-bottom-style" : "solid",
					"text-align" : "center"
				});
				container.addChild(output_11, {
					"top": "270px",
					"left": "641px",
					"width": "95px",
					"height": "35px"
				});
				var inputBox_9 = new cpr.controls.InputBox("POST_NO");
				inputBox_9.readOnly = true;
				inputBox_9.style.css({
					"border-radius" : "0px 5px 5px 0px",
					"text-align" : "center"
				});
				container.addChild(inputBox_9, {
					"top": "270px",
					"left": "735px",
					"width": "120px",
					"height": "35px"
				});
				var output_12 = new cpr.controls.Output();
				output_12.value = "주소";
				output_12.style.css({
					"border-right-style" : "solid",
					"border-bottom-color" : "#cecece",
					"border-top-width" : "1px",
					"border-right-width" : "1px",
					"border-left-color" : "#cecece",
					"border-right-color" : "#cecece",
					"border-left-width" : "1px",
					"border-top-style" : "solid",
					"border-radius" : "5px 0px 0px 5px",
					"background-color" : "#EDEDED",
					"border-left-style" : "solid",
					"border-bottom-width" : "1px",
					"border-top-color" : "#cecece",
					"border-bottom-style" : "solid",
					"text-align" : "center"
				});
				container.addChild(output_12, {
					"top": "330px",
					"left": "641px",
					"width": "95px",
					"height": "35px"
				});
				var inputBox_10 = new cpr.controls.InputBox("ADDR_1");
				inputBox_10.readOnly = true;
				inputBox_10.style.css({
					"border-radius" : "0px 5px 5px 0px",
					"text-align" : "center"
				});
				container.addChild(inputBox_10, {
					"top": "330px",
					"left": "735px",
					"width": "250px",
					"height": "35px"
				});
				var output_13 = new cpr.controls.Output();
				output_13.value = "상세주소";
				output_13.style.css({
					"border-right-style" : "solid",
					"border-bottom-color" : "#cecece",
					"border-top-width" : "1px",
					"border-right-width" : "1px",
					"border-left-color" : "#cecece",
					"border-right-color" : "#cecece",
					"border-left-width" : "1px",
					"border-top-style" : "solid",
					"border-radius" : "5px 0px 0px 5px",
					"background-color" : "#EDEDED",
					"border-left-style" : "solid",
					"border-bottom-width" : "1px",
					"border-top-color" : "#cecece",
					"border-bottom-style" : "solid",
					"text-align" : "center"
				});
				container.addChild(output_13, {
					"top": "390px",
					"left": "641px",
					"width": "95px",
					"height": "35px"
				});
				var inputBox_11 = new cpr.controls.InputBox("ADDR_2");
				inputBox_11.maxLength = 33;
				inputBox_11.style.css({
					"border-radius" : "0px 5px 5px 0px",
					"text-align" : "center"
				});
				container.addChild(inputBox_11, {
					"top": "390px",
					"left": "735px",
					"width": "250px",
					"height": "35px"
				});
				var dateInput_1 = new cpr.controls.DateInput("BIR_DAY");
				dateInput_1.defaultDate = new Date(2000, 0, 1);
				dateInput_1.placeholder = "2000-01-01";
				dateInput_1.style.css({
					"text-align" : "center"
				});
				container.addChild(dateInput_1, {
					"top": "210px",
					"left": "438px",
					"width": "160px",
					"height": "35px"
				});
				var button_1 = new cpr.controls.Button();
				button_1.value = "주소 찾기";
				if(typeof onButtonClick2 == "function") {
					button_1.addEventListener("click", onButtonClick2);
				}
				container.addChild(button_1, {
					"top": "270px",
					"left": "885px",
					"width": "100px",
					"height": "35px"
				});
				var radioButton_1 = new cpr.controls.RadioButton("PERS_COP_TY");
				radioButton_1.style.css({
					"border-right-style" : "solid",
					"border-top-width" : "1px",
					"border-bottom-color" : "#bbbbbb",
					"border-right-width" : "1px",
					"border-left-color" : "#bbbbbb",
					"border-right-color" : "#bbbbbb",
					"border-left-width" : "1px",
					"border-top-style" : "solid",
					"background-color" : "white",
					"border-radius" : "0px 5px 5px 0px",
					"border-left-style" : "solid",
					"border-bottom-width" : "1px",
					"border-top-color" : "#bbbbbb",
					"border-bottom-style" : "solid",
					"text-align" : "center"
				});
				(function(radioButton_1){
					radioButton_1.setItemSet(app.lookup("accountBtn"), {
						"label": "person",
						"value": "value"
					})
				})(radioButton_1);
				if(typeof onPERS_COP_TYSelectionChange == "function") {
					radioButton_1.addEventListener("selection-change", onPERS_COP_TYSelectionChange);
				}
				container.addChild(radioButton_1, {
					"top": "210px",
					"left": "736px",
					"width": "200px",
					"height": "35px"
				});
				var button_2 = new cpr.controls.Button();
				button_2.value = "등 록";
				button_2.style.css({
					"font-size" : "17px"
				});
				if(typeof onButtonClick == "function") {
					button_2.addEventListener("click", onButtonClick);
				}
				container.addChild(button_2, {
					"top": "495px",
					"left": "462px",
					"width": "100px",
					"height": "40px"
				});
				var output_14 = new cpr.controls.Output();
				output_14.enabled = false;
				output_14.value = "은 필수값입니다.";
				output_14.style.css({
					"color" : "red",
					"text-align" : "left"
				});
				container.addChild(output_14, {
					"top": "9px",
					"left": "839px",
					"width": "120px",
					"height": "20px"
				});
				var output_15 = new cpr.controls.Output();
				output_15.value = "* ";
				output_15.style.css({
					"color" : "red",
					"font-weight" : "800",
					"font-size" : "22px",
					"line-height" : "22px",
					"text-align" : "right"
				});
				container.addChild(output_15, {
					"top": "9px",
					"left": "809px",
					"width": "30px",
					"height": "20px"
				});
				var output_16 = new cpr.controls.Output("idNoBox");
				output_16.value = "* ";
				output_16.style.css({
					"color" : "red",
					"font-weight" : "800",
					"font-size" : "22px",
					"line-height" : "22px",
					"text-align" : "right"
				});
				container.addChild(output_16, {
					"top": "210px",
					"left": "37px",
					"width": "30px",
					"height": "20px"
				});
				var output_17 = new cpr.controls.Output("busiNoBox");
				output_17.value = "* ";
				output_17.style.css({
					"color" : "red",
					"font-weight" : "800",
					"font-size" : "22px",
					"line-height" : "22px",
					"text-align" : "right"
				});
				container.addChild(output_17, {
					"top": "270px",
					"left": "37px",
					"width": "30px",
					"height": "20px"
				});
				var output_18 = new cpr.controls.Output();
				output_18.value = "* ";
				output_18.style.css({
					"color" : "red",
					"font-weight" : "800",
					"font-size" : "22px",
					"line-height" : "22px",
					"text-align" : "right"
				});
				container.addChild(output_18, {
					"top": "330px",
					"left": "37px",
					"width": "30px",
					"height": "20px"
				});
				var output_19 = new cpr.controls.Output();
				output_19.value = "* ";
				output_19.style.css({
					"color" : "red",
					"font-weight" : "800",
					"font-size" : "22px",
					"line-height" : "22px",
					"text-align" : "right"
				});
				container.addChild(output_19, {
					"top": "210px",
					"left": "331px",
					"width": "30px",
					"height": "20px"
				});
				var output_20 = new cpr.controls.Output();
				output_20.value = "* ";
				output_20.style.css({
					"color" : "red",
					"font-weight" : "800",
					"font-size" : "22px",
					"line-height" : "22px",
					"text-align" : "right"
				});
				container.addChild(output_20, {
					"top": "270px",
					"left": "331px",
					"width": "30px",
					"height": "20px"
				});
				var output_21 = new cpr.controls.Output();
				output_21.value = "* ";
				output_21.style.css({
					"color" : "red",
					"font-weight" : "800",
					"font-size" : "22px",
					"line-height" : "22px",
					"text-align" : "right"
				});
				container.addChild(output_21, {
					"top": "210px",
					"left": "628px",
					"width": "30px",
					"height": "20px"
				});
			})(group_1);
			container.addChild(group_1, {
				"top": "150px",
				"left": "0px",
				"width": "1024px",
				"height": "598px"
			});
			
			var output_22 = new cpr.controls.Output("title");
			output_22.value = "회원 등록";
			output_22.style.css({
				"font-weight" : "bold",
				"font-size" : "25px",
				"text-align" : "center"
			});
			container.addChild(output_22, {
				"top": "90px",
				"left": "353px",
				"width": "318px",
				"height": "50px"
			});
			if(typeof onBodyLoad == "function"){
				app.addEventListener("load", onBodyLoad);
			}
		}
	});
	app.title = "PosCust";
	cpr.core.Platform.INSTANCE.register(app);
})();
