/*
 * App URI: PosMainMemberSrc
 * Source Location: PosMainMemberSrc.clx
 *
 * This file was generated by eXBuilder6 compiler(1.0.4878), Don't edit manually.
 */
(function() {
	var app = new cpr.core.App("PosMainMemberSrc", { 
		onPrepare: function(loader) {
		},
		onCreate: function(/* cpr.core.AppInstance */ app, exports) {
			var linker = {};
			// Start - User Script
			/************************************************
			 * PosMainMemberSrc.js
			 * Created at 2024. 2. 21. 오전 11:03:33.
			 *
			 * @author sunrise
			 ************************************************/
			var memSerNoList = [];
			/*
			 * 루트 컨테이너에서 init 이벤트 발생 시 호출.
			 * 앱이 최초 구성될 때 발생하는 이벤트 입니다.
			 */
			function onBodyInit(e){
				window.addEventListener("message", function getPostMessage(e) {
					app.lookup("windowOpt").value = e.data;
					
			//		var mobPhNo = e.data;
			//		var mobPhNo = sessionStorage.getItem("MOB_PH_NO");
					var mobPhNo = app.lookup("windowIpb").value;
					var submission = new cpr.protocols.Submission();
					submission.action = '/POS/srcMemInfo.do';
					submission.responseType = "javascript";
					submission.setParameters("MOB_PH_NO", mobPhNo);
					submission.addEventListener("receive", function(e){
						var submi = e.control;
						var jsonObj = JSON.parse(submi.xhr.responseText);
						var grd1 = app.lookup("selectMemInfo");
						var idNo = '';
						var persCopTy = '';
						memSerNoList = [];
						for(var i=0 ; i < jsonObj['memberInfo'].length ; i++){
							if(jsonObj['memberInfo'][i]['PERS_COP_TY'] == '1'){
								idNo = jsonObj['memberInfo'][i]['ID_NO'];
								persCopTy = '개인';
							}else{
								idNo = jsonObj['memberInfo'][i]['BUSI_NO'];
								persCopTy = '법인';
							}
							memSerNoList.push(jsonObj['memberInfo'][i]['MEMB_SER_NO']);
							
							grd1.insertRowData(i, true, {
								MEMB_NM : jsonObj['memberInfo'][i]['MEMB_NM']
								,MOB_PH_NO : jsonObj['memberInfo'][i]['MOB_PH_NO']
								,ID_NO : idNo
								,PERS_COP_TY : persCopTy
							}, false);
						} // for문 종료
						
					});
					submission.send();
				});
			}

			/*
			 * "보내기 버튼" 버튼(btn1)에서 click 이벤트 발생 시 호출.
			 * 사용자가 컨트롤을 클릭할 때 발생하는 이벤트.
			 */
			function onBtn1Click(e){
				
				console.log(memSerNoList);
				var memInfoGrd = app.lookup("selectMemInfo");
				var rowIndex = memInfoGrd.getSelectedRowIndex();
				
				var memInfo = {
					MEMB_NM : memInfoGrd.getCellValue(rowIndex, "MEMB_NM")
					,MOB_PH_NO : memInfoGrd.getCellValue(rowIndex, "MOB_PH_NO")
					,ID_NO : memInfoGrd.getCellValue(rowIndex, "ID_NO")
					,PERS_COP_TY : memInfoGrd.getCellValue(rowIndex, "PERS_COP_TY")
					,MEMB_SER_NO : memSerNoList[rowIndex]
				}
				window.opener.postMessage(memInfo, "*");
				window.close();
			}

			/*
			 * "확 인" 버튼에서 click 이벤트 발생 시 호출.
			 * 사용자가 컨트롤을 클릭할 때 발생하는 이벤트.
			 */
			function onButtonClick(e){
				onBtn1Click(e);
			};
			// End - User Script
			
			// Header
			var dataSet_1 = new cpr.data.DataSet("memInfoList");
			dataSet_1.parseData({
				"columns" : [
					{"name": "MEMB_NM"},
					{"name": "MOB_PH_NO"},
					{"name": "ID_NO"},
					{"name": "PERS_COP_TY"}
				]
			});
			app.register(dataSet_1);
			app.supportMedia("all and (min-width: 1024px)", "default");
			app.supportMedia("all and (min-width: 800px) and (max-width: 1023px)", "new-screen");
			app.supportMedia("all and (min-width: 650px) and (max-width: 799px)", "new-screen2");
			app.supportMedia("all and (min-width: 500px) and (max-width: 649px)", "tablet");
			app.supportMedia("all and (max-width: 499px)", "mobile");
			
			// Configure root container
			var container = app.getContainer();
			container.style.css({
				"width" : "100%",
				"height" : "100%"
			});
			
			// Layout
			var xYLayout_1 = new cpr.controls.layouts.XYLayout();
			container.setLayout(xYLayout_1);
			
			// UI Configuration
			var group_1 = new cpr.controls.Container();
			var xYLayout_2 = new cpr.controls.layouts.XYLayout();
			group_1.setLayout(xYLayout_2);
			(function(container){
				var grid_1 = new cpr.controls.Grid("selectMemInfo");
				grid_1.init({
					"dataSet": app.lookup("memInfoList"),
					"columns": [
						{"width": "135px"},
						{"width": "101px"},
						{"width": "114px"},
						{"width": "110px"}
					],
					"header": {
						"rows": [{"height": "24px"}],
						"cells": [
							{
								"constraint": {"rowIndex": 0, "colIndex": 0},
								"configurator": function(cell){
									cell.text = "회원이름";
								}
							},
							{
								"constraint": {"rowIndex": 0, "colIndex": 1},
								"configurator": function(cell){
									cell.text = "전화번호";
								}
							},
							{
								"constraint": {"rowIndex": 0, "colIndex": 2},
								"configurator": function(cell){
									cell.text = "주민 / 법인번호";
								}
							},
							{
								"constraint": {"rowIndex": 0, "colIndex": 3},
								"configurator": function(cell){
									cell.text = "구분";
								}
							}
						]
					},
					"detail": {
						"rows": [{"height": "24px"}],
						"cells": [
							{
								"constraint": {"rowIndex": 0, "colIndex": 0},
								"configurator": function(cell){
									cell.columnName = "MEMB_NM";
								}
							},
							{
								"constraint": {"rowIndex": 0, "colIndex": 1},
								"configurator": function(cell){
									cell.columnName = "MOB_PH_NO";
									cell.control = (function(){
										var output_1 = new cpr.controls.Output();
										output_1.style.css({
											"text-align" : "center"
										});
										output_1.bind("value").toDataColumn("MOB_PH_NO");
										return output_1;
									})();
								}
							},
							{
								"constraint": {"rowIndex": 0, "colIndex": 2},
								"configurator": function(cell){
									cell.columnName = "ID_NO";
									cell.control = (function(){
										var output_2 = new cpr.controls.Output();
										output_2.style.css({
											"text-align" : "center"
										});
										output_2.bind("value").toDataColumn("ID_NO");
										return output_2;
									})();
								}
							},
							{
								"constraint": {"rowIndex": 0, "colIndex": 3},
								"configurator": function(cell){
									cell.columnName = "PERS_COP_TY";
									cell.control = (function(){
										var output_3 = new cpr.controls.Output();
										output_3.style.css({
											"text-align" : "center"
										});
										output_3.bind("value").toDataColumn("PERS_COP_TY");
										return output_3;
									})();
								}
							}
						]
					}
				});
				container.addChild(grid_1, {
					"top": "20px",
					"left": "20px",
					"width": "580px",
					"height": "528px"
				});
				var button_1 = new cpr.controls.Button();
				button_1.value = "확 인";
				if(typeof onButtonClick == "function") {
					button_1.addEventListener("click", onButtonClick);
				}
				container.addChild(button_1, {
					"top": "571px",
					"left": "275px",
					"width": "70px",
					"height": "25px"
				});
				var inputBox_1 = new cpr.controls.InputBox("windowIpb");
				inputBox_1.visible = false;
				inputBox_1.placeholder = "전송할 값을 입력해주세요.";
				container.addChild(inputBox_1, {
					"top": "595px",
					"left": "296px",
					"width": "1px",
					"height": "1px"
				});
				var button_2 = new cpr.controls.Button("btn1");
				button_2.visible = false;
				button_2.value = "보내기 버튼";
				if(typeof onBtn1Click == "function") {
					button_2.addEventListener("click", onBtn1Click);
				}
				container.addChild(button_2, {
					"top": "595px",
					"left": "296px",
					"width": "1px",
					"height": "1px"
				});
				var output_4 = new cpr.controls.Output("windowOpt");
				output_4.visible = false;
				output_4.value = "메인 앱에서 값 받아오기";
				output_4.style.css({
					"border-right-style" : "solid",
					"border-top-width" : "1px",
					"border-bottom-color" : "black",
					"border-right-width" : "1px",
					"padding-left" : "5px",
					"border-left-color" : "black",
					"border-right-color" : "black",
					"border-left-width" : "1px",
					"border-top-style" : "solid",
					"border-left-style" : "solid",
					"border-bottom-width" : "1px",
					"border-top-color" : "black",
					"border-bottom-style" : "solid"
				});
				container.addChild(output_4, {
					"top": "595px",
					"left": "296px",
					"width": "1px",
					"height": "1px"
				});
			})(group_1);
			container.addChild(group_1, {
				"top": "30px",
				"left": "10px",
				"width": "620px",
				"height": "650px"
			});
			
			var output_5 = new cpr.controls.Output("PH_NO");
			output_5.value = "";
			container.addChild(output_5, {
				"top": "10px",
				"left": "24px",
				"width": "100px",
				"height": "20px"
			});
			if(typeof onBodyInit == "function"){
				app.addEventListener("init", onBodyInit);
			}
		}
	});
	app.title = "PosMainMemberSrc";
	cpr.core.Platform.INSTANCE.register(app);
})();
