/*
 * App URI: PosProductSearch
 * Source Location: PosProductSearch.clx
 *
 * This file was generated by eXBuilder6 compiler(1.0.4878), Don't edit manually.
 */
(function() {
	var app = new cpr.core.App("PosProductSearch", { 
		onPrepare: function(loader) {
		},
		onCreate: function(/* cpr.core.AppInstance */ app, exports) {
			var linker = {};
			// Start - User Script
			/************************************************
			 * PosProductSearch.js
			 * Created at 2024. 2. 27. 오후 1:20:50.
			 *
			 * @author sunrise
			 ************************************************/

			/*
			 * 루트 컨테이너에서 init 이벤트 발생 시 호출.
			 * 앱이 최초 구성될 때 발생하는 이벤트 입니다.
			 */
			function onBodyInit(e){
				app.lookup("prodCls").selectItem(0);
			}

			/*
			 * 콤보 박스에서 selection-change 이벤트 발생 시 호출.
			 * ComboBox Item을 선택하여 선택된 값이 저장된 후에 발생하는 이벤트.
			 */
			function onProdClsSelectionChange(e){
				var prodCls = e.control;
			//	console.log(app.lookup("prodCls").value);
			};
			// End - User Script
			
			// Header
			var dataSet_1 = new cpr.data.DataSet("productList");
			dataSet_1.parseData({
				"columns" : [
					{"name": "PROD_CD"},
					{"name": "PROD_CLS_CD"},
					{"name": "PROD_NM"},
					{"name": "PROD_ENG_NM"},
					{"name": "ORIG_NAT"},
					{"name": "PURC_PR"},
					{"name": "SELL_PR"},
					{"name": "BAR_CODE"},
					{
						"name": "CLIENT_NM",
						"dataType": "string"
					},
					{"name": "COLOR"},
					{"name": "PROD_SIZE"},
					{"name": "SALE_OR_NOT"},
					{"name": "SALE_PR"},
					{"name": "TAXAT_TY"},
					{"name": "MEM_POINT"}
				]
			});
			app.register(dataSet_1);
			
			var dataSet_2 = new cpr.data.DataSet("prodClsTbl");
			dataSet_2.parseData({
				"columns": [
					{"name": "PROD_CLS_NM"},
					{"name": "PROD_CLS_CD"},
					{"name": "REMARKS"}
				],
				"rows": [
					{"PROD_CLS_NM": "전체", "PROD_CLS_CD": "0", "REMARKS": "전체"},
					{"PROD_CLS_NM": "가공식품", "PROD_CLS_CD": "001", "REMARKS": "이미 한번 가공된 식품류(라면, 과자, 음료, 통조림 등등)"},
					{"PROD_CLS_NM": "신선식품", "PROD_CLS_CD": "002", "REMARKS": "야채, 과일, 육류, 어류 등등"},
					{"PROD_CLS_NM": "디지털/가전", "PROD_CLS_CD": "003", "REMARKS": "디지털/가전제품류"},
					{"PROD_CLS_NM": "의류", "PROD_CLS_CD": "004", "REMARKS": "상의, 하의, 신발, 모자 등등"},
					{"PROD_CLS_NM": "일상용품", "PROD_CLS_CD": "005", "REMARKS": "세면용품, 청소용품 등등"}
				]
			});
			app.register(dataSet_2);
			app.supportMedia("all and (min-width: 1024px)", "default");
			app.supportMedia("all and (min-width: 500px) and (max-width: 1023px)", "tablet");
			app.supportMedia("all and (max-width: 499px)", "mobile");
			
			// Configure root container
			var container = app.getContainer();
			container.style.css({
				"width" : "100%",
				"height" : "100%"
			});
			
			// Layout
			var xYLayout_1 = new cpr.controls.layouts.XYLayout();
			container.setLayout(xYLayout_1);
			
			// UI Configuration
			var embeddedApp_1 = new cpr.controls.EmbeddedApp("ea1");
			cpr.core.App.load("PosHeader", function(app) {
				if(app){
					embeddedApp_1.app = app;
				}
			});
			container.addChild(embeddedApp_1, {
				"top": "0px",
				"left": "0px",
				"width": "1024px",
				"height": "80px"
			});
			
			var hTMLSnippet_1 = new cpr.controls.HTMLSnippet();
			hTMLSnippet_1.value = "상품 조회 내역";
			hTMLSnippet_1.style.css({
				"border-right-style" : "solid",
				"border-top-width" : "1px",
				"color" : "white",
				"border-right-width" : "1px",
				"vertical-align" : "middle",
				"border-left-width" : "1px",
				"border-top-style" : "solid",
				"background-color" : "black",
				"border-radius" : "25px",
				"border-left-style" : "solid",
				"border-bottom-width" : "1px",
				"border-bottom-style" : "solid",
				"text-align" : "center"
			});
			container.addChild(hTMLSnippet_1, {
				"top": "150px",
				"left": "20px",
				"width": "120px",
				"height": "30px"
			});
			
			var group_1 = new cpr.controls.Container();
			group_1.style.css({
				"background-color" : "#E0E0E0"
			});
			var xYLayout_2 = new cpr.controls.layouts.XYLayout();
			group_1.setLayout(xYLayout_2);
			(function(container){
				var inputBox_1 = new cpr.controls.InputBox("PROD_NM");
				inputBox_1.placeholder = "상품명";
				inputBox_1.maxLength = 11;
				inputBox_1.inputMode = "tel";
				inputBox_1.inputFilter = "[0-9]";
				container.addChild(inputBox_1, {
					"top": "10px",
					"left": "410px",
					"width": "200px",
					"height": "25px"
				});
				var inputBox_2 = new cpr.controls.InputBox("BAR_CODE");
				inputBox_2.placeholder = "바코드 번호";
				inputBox_2.maxLength = 20;
				inputBox_2.inputFilter = "[0-9]";
				container.addChild(inputBox_2, {
					"top": "10px",
					"left": "200px",
					"width": "200px",
					"height": "25px"
				});
				var button_1 = new cpr.controls.Button("srcBtn");
				button_1.value = "조회";
				container.addChild(button_1, {
					"top": "10px",
					"left": "905px",
					"width": "56px",
					"height": "25px"
				});
				var inputBox_3 = new cpr.controls.InputBox("CLIENT_NO");
				inputBox_3.placeholder = "거래처 명";
				inputBox_3.maxLength = 11;
				inputBox_3.inputMode = "tel";
				inputBox_3.inputFilter = "[0-9]";
				container.addChild(inputBox_3, {
					"top": "10px",
					"left": "620px",
					"width": "200px",
					"height": "25px"
				});
				var comboBox_1 = new cpr.controls.ComboBox("prodCls");
				comboBox_1.treeExpandDepth = 1;
				comboBox_1.preventInput = true;
				(function(comboBox_1){
					comboBox_1.setItemSet(app.lookup("prodClsTbl"), {
						"label": "PROD_CLS_NM",
						"value": "PROD_CLS_CD",
						"tooltip": "REMARKS"
					});
				})(comboBox_1);
				if(typeof onProdClsSelectionChange == "function") {
					comboBox_1.addEventListener("selection-change", onProdClsSelectionChange);
				}
				container.addChild(comboBox_1, {
					"top": "10px",
					"left": "10px",
					"width": "180px",
					"height": "25px"
				});
			})(group_1);
			container.addChild(group_1, {
				"top": "90px",
				"left": "20px",
				"width": "984px",
				"height": "50px"
			});
			
			var grid_1 = new cpr.controls.Grid("grd1");
			grid_1.init({
				"hScroll": "hidden",
				"showDeletedRow": false,
				"columns": [
					{"width": "58px"},
					{"width": "149px"},
					{"width": "154px"},
					{"width": "84px"},
					{"width": "70px"},
					{"width": "65px"},
					{"width": "90px"},
					{"width": "68px"},
					{"width": "62px"},
					{"width": "78px"},
					{"width": "105px"}
				],
				"header": {
					"rows": [{"height": "24px"}],
					"cells": [
						{
							"constraint": {"rowIndex": 0, "colIndex": 0},
							"configurator": function(cell){
								cell.text = "상품코드";
								cell.style.css({
									"font-size" : "13px",
									"text-align" : "center"
								});
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 2, "rowSpan": 1, "colSpan": 1},
							"configurator": function(cell){
								cell.text = "상품명";
								cell.style.css({
									"font-size" : "13px",
									"text-align" : "center"
								});
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 3, "rowSpan": 1, "colSpan": 1},
							"configurator": function(cell){
								cell.text = "원산지";
								cell.style.css({
									"font-size" : "13px",
									"text-align" : "center"
								});
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 4},
							"configurator": function(cell){
								cell.text = "원가";
								cell.style.css({
									"font-size" : "13px",
									"text-align" : "center"
								});
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 6, "rowSpan": 1, "colSpan": 1},
							"configurator": function(cell){
								cell.text = "판매가";
								cell.style.css({
									"font-size" : "13px",
									"text-align" : "center"
								});
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 5, "rowSpan": 1, "colSpan": 1},
							"configurator": function(cell){
								cell.text = "세일가격";
								cell.style.css({
									"font-size" : "13px",
									"text-align" : "center"
								});
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 10, "rowSpan": 1, "colSpan": 1},
							"configurator": function(cell){
								cell.text = "거래처 명";
								cell.style.css({
									"font-size" : "13px",
									"text-align" : "center"
								});
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 1},
							"configurator": function(cell){
								cell.text = "바코드";
								cell.style.css({
									"font-size" : "13px",
									"text-align" : "center"
								});
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 7},
							"configurator": function(cell){
								cell.text = "적립금";
								cell.style.css({
									"font-size" : "13px",
									"text-align" : "center"
								});
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 9},
							"configurator": function(cell){
								cell.text = "사이즈";
								cell.style.css({
									"font-size" : "13px"
								});
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 8},
							"configurator": function(cell){
								cell.text = "색상";
								cell.style.css({
									"font-size" : "13px"
								});
							}
						}
					]
				},
				"detail": {
					"rows": [{"height": "24px"}],
					"cells": [
						{
							"constraint": {"rowIndex": 0, "colIndex": 0},
							"configurator": function(cell){
								cell.control = (function(){
									var output_1 = new cpr.controls.Output();
									output_1.style.css({
										"font-size" : "12px",
										"text-align" : "center"
									});
									output_1.bind("value").toDataSet(app.lookup("productList"), "PROD_CD", 0);
									return output_1;
								})();
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 1},
							"configurator": function(cell){
								cell.control = (function(){
									var output_2 = new cpr.controls.Output();
									output_2.style.css({
										"font-size" : "12px",
										"text-align" : "center"
									});
									output_2.bind("value").toDataSet(app.lookup("productList"), "BAR_CODE", 0);
									return output_2;
								})();
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 2},
							"configurator": function(cell){
								cell.control = (function(){
									var output_3 = new cpr.controls.Output();
									output_3.style.css({
										"font-size" : "12px",
										"text-align" : "center"
									});
									output_3.bind("value").toDataSet(app.lookup("productList"), "PROD_NM", 0);
									return output_3;
								})();
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 3},
							"configurator": function(cell){
								cell.control = (function(){
									var output_4 = new cpr.controls.Output();
									output_4.style.css({
										"font-size" : "12px",
										"text-align" : "center"
									});
									output_4.bind("value").toDataSet(app.lookup("productList"), "ORIG_NAT", 0);
									return output_4;
								})();
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 4},
							"configurator": function(cell){
								cell.control = (function(){
									var output_5 = new cpr.controls.Output();
									output_5.style.css({
										"font-size" : "12px",
										"text-align" : "center"
									});
									output_5.bind("value").toDataSet(app.lookup("productList"), "PURC_PR", 0);
									return output_5;
								})();
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 5},
							"configurator": function(cell){
								cell.control = (function(){
									var output_6 = new cpr.controls.Output();
									output_6.style.css({
										"font-size" : "12px",
										"text-align" : "center"
									});
									output_6.bind("value").toDataSet(app.lookup("productList"), "SALE_PR", 0);
									return output_6;
								})();
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 6},
							"configurator": function(cell){
								cell.control = (function(){
									var output_7 = new cpr.controls.Output();
									output_7.style.css({
										"font-size" : "12px",
										"text-align" : "center"
									});
									output_7.bind("value").toDataSet(app.lookup("productList"), "SELL_PR", 0);
									return output_7;
								})();
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 7},
							"configurator": function(cell){
								cell.control = (function(){
									var output_8 = new cpr.controls.Output();
									output_8.style.css({
										"font-size" : "12px",
										"text-align" : "center"
									});
									output_8.bind("value").toDataSet(app.lookup("productList"), "MEM_POINT", 0);
									return output_8;
								})();
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 8},
							"configurator": function(cell){
								cell.control = (function(){
									var output_9 = new cpr.controls.Output();
									output_9.style.css({
										"font-size" : "12px",
										"text-align" : "center"
									});
									output_9.bind("value").toDataSet(app.lookup("productList"), "COLOR", 0);
									return output_9;
								})();
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 9},
							"configurator": function(cell){
								cell.control = (function(){
									var output_10 = new cpr.controls.Output();
									output_10.style.css({
										"font-size" : "12px",
										"text-align" : "center"
									});
									output_10.bind("value").toDataSet(app.lookup("productList"), "PROD_SIZE", 0);
									return output_10;
								})();
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 10},
							"configurator": function(cell){
								cell.control = (function(){
									var output_11 = new cpr.controls.Output();
									output_11.style.css({
										"font-size" : "12px",
										"text-align" : "center"
									});
									output_11.bind("value").toDataSet(app.lookup("productList"), "CLIENT_NM", 0);
									return output_11;
								})();
							}
						}
					]
				}
			});
			container.addChild(grid_1, {
				"top": "190px",
				"left": "20px",
				"width": "984px",
				"height": "558px"
			});
			if(typeof onBodyInit == "function"){
				app.addEventListener("init", onBodyInit);
			}
		}
	});
	app.title = "PosProductSearch";
	cpr.core.Platform.INSTANCE.register(app);
})();
