/*
 * App URI: PosProductRegist2
 * Source Location: PosProductRegist2.clx
 *
 * This file was generated by eXBuilder6 compiler(1.0.4878), Don't edit manually.
 */
(function() {
	var app = new cpr.core.App("PosProductRegist2", { 
		onPrepare: function(loader) {
		},
		onCreate: function(/* cpr.core.AppInstance */ app, exports) {
			var linker = {};
			// Start - User Script
			/************************************************
			 * POSProductRegist2.js
			 * Created at 2024. 1. 21. 오후 10:39:49.
			 *
			 * @author sunrise
			 ************************************************/


			/*
			 * 서치 인풋에서 value-change 이벤트 발생 시 호출.
			 * SearchInput의 value를 변경하여 변경된 값이 저장된 후에 발생하는 이벤트.
			 */
			function onSearchInputValueChange(e){
				var searchInput = app.lookup("srcAccount").value;
				var submission = new cpr.protocols.Submission();
				submission.action = '/POS/clientSearch.do';
				submission.responseType = 'text';
				submission.async = false;
				submission.setParameters("CLIENT_NM", searchInput);
				submission.send();
				
				var grd1 = app.lookup("grd1");
				grd1.redraw();
				
				console.log(searchInput);
				
			}


			/*
			 * "확 인" 버튼에서 click 이벤트 발생 시 호출.
			 * 사용자가 컨트롤을 클릭할 때 발생하는 이벤트.
			 */
			function onButtonClick(e){
				
				window.opener.postMessage(app.lookup("grd1").getSelectionData(), "*");
				// 선택된 거래처 명
			//	var grd1 = app.lookup("grd1").getSelectionData();
			//	console.log(grd1);
				window.close();
			};
			// End - User Script
			
			// Header
			var dataSet_1 = new cpr.data.DataSet("clientList");
			dataSet_1.parseData({
				"columns": [{"name": "거래처명"}],
				"rows": [
					{"거래처명": "거래처 A"},
					{"거래처명": "거래처 B"},
					{"거래처명": "거래처 C"},
					{"거래처명": "거래처 D"},
					{"거래처명": "거래처 E"}
				]
			});
			app.register(dataSet_1);
			var dataMap_1 = new cpr.data.DataMap("CLIENT");
			dataMap_1.parseData({
				"columns" : [{"name": "CLIENT_NM"}]
			});
			app.register(dataMap_1);
			app.supportMedia("all", "new-screen");
			
			// Configure root container
			var container = app.getContainer();
			container.style.css({
				"width" : "100%",
				"height" : "100%"
			});
			
			// Layout
			var xYLayout_1 = new cpr.controls.layouts.XYLayout();
			container.setLayout(xYLayout_1);
			
			// UI Configuration
			var searchInput_1 = new cpr.controls.SearchInput("srcAccount");
			searchInput_1.placeholder = "거래처 명";
			if(typeof onSearchInputValueChange == "function") {
				searchInput_1.addEventListener("value-change", onSearchInputValueChange);
			}
			container.addChild(searchInput_1, {
				"top": "75px",
				"left": "20px",
				"width": "360px",
				"height": "35px"
			});
			
			var output_1 = new cpr.controls.Output();
			output_1.value = "  거래처 검색";
			output_1.style.css({
				"border-bottom-color" : "#D0D0D0",
				"font-weight" : "bold",
				"border-bottom-width" : "4px",
				"font-size" : "20px",
				"border-bottom-style" : "solid"
			});
			container.addChild(output_1, {
				"top": "20px",
				"left": "20px",
				"width": "360px",
				"height": "45px"
			});
			
			var grid_1 = new cpr.controls.Grid("grd1");
			grid_1.init({
				"dataSet": app.lookup("clientList"),
				"columns": [{"width": "100px"}],
				"header": {
					"rows": [{"height": "24px"}],
					"cells": [{
						"constraint": {"rowIndex": 0, "colIndex": 0},
						"configurator": function(cell){
							cell.filterable = false;
							cell.sortable = false;
							cell.targetColumnName = "거래처명";
							cell.text = "거래처명";
							cell.style.css({
								"vertical-align" : "middle",
								"text-align" : "left"
							});
						}
					}]
				},
				"detail": {
					"rows": [{"height": "24px"}],
					"cells": [{
						"constraint": {"rowIndex": 0, "colIndex": 0},
						"configurator": function(cell){
							cell.columnName = "거래처명";
							cell.style.css({
								"vertical-align" : "middle",
								"text-align" : "left"
							});
						}
					}]
				}
			});
			grid_1.bind("rowIndexerStartNum").toDataMap(app.lookup("CLIENT"), "CLIENT_NM");
			container.addChild(grid_1, {
				"top": "120px",
				"left": "20px",
				"width": "360px",
				"height": "425px"
			});
			
			var button_1 = new cpr.controls.Button();
			button_1.value = "확 인";
			if(typeof onButtonClick == "function") {
				button_1.addEventListener("click", onButtonClick);
			}
			container.addChild(button_1, {
				"top": "555px",
				"left": "165px",
				"width": "70px",
				"height": "25px"
			});
		}
	});
	app.title = "PosProductRegist2";
	cpr.core.Platform.INSTANCE.register(app);
})();
