/*
 * App URI: PosProductRegist1
 * Source Location: PosProductRegist1.clx
 *
 * This file was generated by eXBuilder6 compiler(1.0.4878), Don't edit manually.
 */
(function() {
	var app = new cpr.core.App("PosProductRegist1", { 
		onPrepare: function(loader) {
		},
		onCreate: function(/* cpr.core.AppInstance */ app, exports) {
			var linker = {};
			// Start - User Script
			/************************************************
			 * POSProductRegist.js
			 * Created at 2024. 1. 19. 오후 3:38:05.
			 *
			 * @author sunrise
			 ************************************************/
			//var util = createCommonUtil();
			var openWindow = null;

			function onBodyInit(e){
				var cmb1 = app.lookup("PROD_CLS_CD");
				cmb1.selectItem(0);
				
				window.addEventListener("message", function getPostMessage(e) {
					if (app.lookup("CLIENT_NM") != null) {
						app.lookup("CLIENT_NM").value = e.data;
					}
				});
				
				var submission = new cpr.protocols.Submission();
				submission.action = '/POS/productPageInit.do';
				submission.responseType = 'text';
				submission.async = false;
				submission.send();
				var prodCd = submission.getParameters("PROD_CD");
				var prod = submission.getRequestData("PROD_CD");
				var pro = submission.getResponseData("PROD_CD");
				var pr = submission.getParameterNames("PROD_CD");
				var p = submission.getUserAttrNames();
				debugger
				app.lookup("PROD_CD").value = prodCd;
				
			}

			/*
			 * 체크 박스에서 value-change 이벤트 발생 시 호출.
			 */
			function onCbx2ValueChange(e){
				var cbx2 = app.lookup("SALE_OR_NOT").value;
				var ipb9 = app.lookup("SALE_PR");
				if(cbx2 === 'true'){
					ipb9.readOnly = false;
				}else{
					ipb9.readOnly = true;
					ipb9.value = '';
				}
			}

			/*
			 * "검색" 버튼에서 click 이벤트 발생 시 호출.
			 * 사용자가 컨트롤을 클릭할 때 발생하는 이벤트.
			 */
			function onButtonClick(e){
				
				openWindow = window.open("/POS/PosProductRegist2.do", "_popup", "height=600,left=100,top=100,width=400,location=no,menubar=no,resizable=no,scrollbars=yes,status=yes,titlebar=no,toolbar=no");		
				
			}

			/*
			 * "등 록" 버튼에서 click 이벤트 발생 시 호출.
			 * 사용자가 컨트롤을 클릭할 때 발생하는 이벤트.
			 */
			function onButtonClick2(e){
				
				if(checkDupl() == true){
					
					var prodClsCd = app.lookup("PROD_CLS_CD");
					var prodNm = app.lookup("PROD_NM");
					var prodEngNm = app.lookup("PROD_ENG_NM");
					var origNat = app.lookup("ORIG_NAT");
					var purcPr = app.lookup("PURC_PR");
					var sellPr = app.lookup("SELL_PR");
					var barCode = app.lookup("BAR_CODE");
					
					// CLIENT_NO 를 가져와야하는데 어떻게 가져올지 생각....
					var clientNo = app.lookup("CLIENT_NM");
					var color = app.lookup("COLOR");
					var prodSize = app.lookup("PROD_SIZE");
					var saleOrNot = app.lookup("SALE_OR_NOT");
					if(saleOrNot.checked){
						saleOrNot.value = '1'; // 세일
					}else{
						saleOrNot.value = '0'; // 세일X
					}
					
					var salePr = app.lookup("SALE_PR");
					var taxatTy = app.lookup("TAXAT_TY");
					if(taxatTy.checked){
						taxatTy.value = '2'; // 과세
					}else{
						taxatTy.value = '1'; // 비과세
					}
					
					var memPoint = app.lookup("MEM_POINT");
					if(memPoint.value = ''){
						memPoint.value = '0';
					}
					
					var submission = new cpr.protocols.Submission();
					submission.action = '/POS/productInsert.do';
					submission.responseType = 'text';
					submission.async = false;
					submission.setParameters("PROD_CLS_CD", prodClsCd.value);
					submission.setParameters("PROD_NM", prodNm.value);
					submission.setParameters("PROD_ENG_NM", prodEngNm.value);
					submission.setParameters("ORIG_NAT", origNat.value);
					submission.setParameters("PURC_PR", purcPr.value);
					submission.setParameters("SELL_PR", sellPr.value);
					submission.setParameters("BAR_CODE", barCode.value);
					submission.setParameters("CLIENT_NO", '7777');
			//		submission.setParameters("CLIENT_NO", clientNo.value);
					submission.setParameters("COLOR", color.value);
					submission.setParameters("PROD_SIZE", prodSize.value);
					submission.setParameters("SALE_OR_NOT", saleOrNot.value);
					submission.setParameters("SALE_PR", salePr.value);
					submission.setParameters("TAXAT_TY", taxatTy.value);
					submission.setParameters("MEM_POINT", memPoint.value);
					
					submission.send();
					alert('상품이 등록됐습니다.');
				}else{
					alert('등록이 실패했습니다.');
				}
			}

			// 유효성 검사
			function checkDupl(){
				var prodNm = app.lookup("PROD_NM").value;
				var prodEngNm = app.lookup("PROD_ENG_NM").value;
				var origNat = app.lookup("ORIG_NAT").value;
				var purcPr = app.lookup("PURC_PR").value;
				var sellPr = app.lookup("SELL_PR").value;
				var barCode = app.lookup("BAR_CODE").value;
				var clientNo = app.lookup("CLIENT_NM").value;
				var prodSize = app.lookup("PROD_SIZE").value;
				var saleOrNot = app.lookup("SALE_OR_NOT");
				var salePr = app.lookup("SALE_PR").value;
				
				if(prodNm == ''){
					alert('상품명 입력은 필수입니다.');
					return false;
				}
				if(prodEngNm == ''){
					alert('상품명(영어) 입력은 필수입니다.');
					return false;
				}
				if(origNat == ''){
					alert('원산지 입력은 필수입니다.');
					return false;
				}
				if(purcPr == ''){
					alert('원가 입력은 필수입니다.');
					return false;
				}
				if(sellPr == ''){
					alert('판매가 입력은 필수입니다.');
					return false;
				}
				if(barCode == ''){
					alert('바코드 입력은 필수입니다.');
					return false;
				}
				var origNatList = {origNat :['KO', 'Ko', 'ko', 'KOREA', 'Korea', 'korea', '한국', '대한민국']};
				if(barCode.substr(0,3) == '880'){
			//		if(!origNat in origNatList){
					if(origNat == 'KO' || origNat == "ko" || origNat == "KOREA" || origNat == "Korea" || origNat == "korea" || origNat == "한국" || origNat == "대한민국"){
					}else{
						alert('원산지와 바코드의 국가가 일치하지 않습니다.');
						return false;
					}
				}
				if(origNat == "KO" || origNat == "ko" || origNat == "KOREA" || origNat == "Korea" || origNat == "korea" || origNat == "한국" || origNat == "대한민국"){
					if(barCode.substr(0, 3) != '880'){
						alert('바코드의 국가식별코드가 올바르지 않습니다.');
						return false;
					}
				}
				if(clientNo == ''){
					alert('거래처 입력은 필수입니다.');
					return false;
				}
			//	사이즈 정규식.test? 해야할까
			//	if(prodSize == ''){
			//		alert('');
			//		return false;
			//	}
				if(saleOrNot.checked == true){
					if(salePr == ''){
						alert('세일여부 체크시 세일가격 입력은 필수입니다.');
						return false;
					}
					if(salePr.length < 3){
						alert('세일가격은 백단위부터 가능합니다.');
						return false;
					}
				}
				return true;
			};
			// End - User Script
			
			// Header
			var dataSet_1 = new cpr.data.DataSet("prodClsCd");
			dataSet_1.parseData({
				"columns": [
					{"name": "label"},
					{"name": "value"}
				],
				"rows": [
					{"label": "육류", "value": "1"},
					{"label": "쌀", "value": "2"},
					{"label": "음료", "value": "3"}
				]
			});
			app.register(dataSet_1);
			app.supportMedia("all and (min-width: 1024px)", "default");
			app.supportMedia("all and (min-width: 500px) and (max-width: 1023px)", "tablet");
			app.supportMedia("all and (max-width: 499px)", "mobile");
			
			// Configure root container
			var container = app.getContainer();
			container.style.css({
				"width" : "100%",
				"height" : "100%"
			});
			
			// Layout
			var xYLayout_1 = new cpr.controls.layouts.XYLayout();
			container.setLayout(xYLayout_1);
			
			// UI Configuration
			var group_1 = new cpr.controls.Container("grp1");
			group_1.style.css({
				"background-color" : "#E0E0E0"
			});
			var xYLayout_2 = new cpr.controls.layouts.XYLayout();
			group_1.setLayout(xYLayout_2);
			(function(container){
				var output_1 = new cpr.controls.Output();
				output_1.value = "상품 코드 :";
				output_1.style.css({
					"text-align" : "center"
				});
				container.addChild(output_1, {
					"top": "50px",
					"left": "80px",
					"width": "100px",
					"height": "50px"
				});
				var output_2 = new cpr.controls.Output();
				output_2.value = "상품명(한글) :";
				output_2.style.css({
					"text-align" : "center"
				});
				container.addChild(output_2, {
					"top": "120px",
					"left": "80px",
					"width": "100px",
					"height": "50px"
				});
				var output_3 = new cpr.controls.Output();
				output_3.value = "상품명(영어) :";
				output_3.style.css({
					"text-align" : "center"
				});
				container.addChild(output_3, {
					"top": "190px",
					"left": "80px",
					"width": "100px",
					"height": "50px"
				});
				var output_4 = new cpr.controls.Output();
				output_4.value = "원산지 :";
				output_4.style.css({
					"text-align" : "center"
				});
				container.addChild(output_4, {
					"top": "260px",
					"left": "80px",
					"width": "100px",
					"height": "50px"
				});
				var output_5 = new cpr.controls.Output();
				output_5.value = "바코드 번호 :";
				output_5.style.css({
					"text-align" : "center"
				});
				container.addChild(output_5, {
					"top": "330px",
					"left": "80px",
					"width": "100px",
					"height": "50px"
				});
				var output_6 = new cpr.controls.Output("PROD_CD");
				output_6.style.css({
					"text-align" : "center"
				});
				container.addChild(output_6, {
					"top": "50px",
					"left": "190px",
					"width": "130px",
					"height": "50px"
				});
				var inputBox_1 = new cpr.controls.InputBox("PROD_NM");
				inputBox_1.placeholder = "상품명(한글)";
				inputBox_1.maxLength = 13;
				inputBox_1.inputFilter = "[ㄱ-힣0-9]";
				inputBox_1.style.css({
					"text-align" : "center"
				});
				container.addChild(inputBox_1, {
					"top": "120px",
					"left": "179px",
					"width": "141px",
					"height": "50px"
				});
				var inputBox_2 = new cpr.controls.InputBox("PROD_ENG_NM");
				inputBox_2.placeholder = "상품명(영어)";
				inputBox_2.maxLength = 40;
				inputBox_2.inputFilter = "[a-zA-Z0-9]";
				inputBox_2.style.css({
					"text-align" : "center"
				});
				container.addChild(inputBox_2, {
					"top": "190px",
					"left": "179px",
					"width": "141px",
					"height": "50px"
				});
				var inputBox_3 = new cpr.controls.InputBox("ORIG_NAT");
				inputBox_3.placeholder = "원산지";
				inputBox_3.maxLength = 7;
				inputBox_3.inputFilter = "[ㄱ-힣]";
				inputBox_3.style.css({
					"text-align" : "center"
				});
				container.addChild(inputBox_3, {
					"top": "260px",
					"left": "179px",
					"width": "141px",
					"height": "50px"
				});
				var inputBox_4 = new cpr.controls.InputBox("BAR_CODE");
				inputBox_4.placeholder = "바코드 번호";
				inputBox_4.maxLength = 20;
				inputBox_4.inputFilter = "[0-9]";
				inputBox_4.style.css({
					"text-align" : "center"
				});
				container.addChild(inputBox_4, {
					"top": "330px",
					"left": "179px",
					"width": "141px",
					"height": "50px"
				});
				var output_7 = new cpr.controls.Output();
				output_7.value = "가격(원가) :";
				output_7.style.css({
					"text-align" : "center"
				});
				container.addChild(output_7, {
					"top": "50px",
					"left": "355px",
					"width": "100px",
					"height": "50px"
				});
				var output_8 = new cpr.controls.Output();
				output_8.value = "가격(판매가) :";
				output_8.style.css({
					"text-align" : "center"
				});
				container.addChild(output_8, {
					"top": "120px",
					"left": "355px",
					"width": "100px",
					"height": "50px"
				});
				var output_9 = new cpr.controls.Output();
				output_9.value = "상품 분류 :";
				output_9.style.css({
					"text-align" : "center"
				});
				container.addChild(output_9, {
					"top": "189px",
					"left": "355px",
					"width": "100px",
					"height": "50px"
				});
				var output_10 = new cpr.controls.Output();
				output_10.value = "과세 여부 :";
				output_10.style.css({
					"text-align" : "center"
				});
				container.addChild(output_10, {
					"top": "260px",
					"left": "355px",
					"width": "100px",
					"height": "50px"
				});
				var output_11 = new cpr.controls.Output();
				output_11.value = "회원 포인트 :";
				output_11.style.css({
					"text-align" : "center"
				});
				container.addChild(output_11, {
					"top": "330px",
					"left": "355px",
					"width": "100px",
					"height": "50px"
				});
				var inputBox_5 = new cpr.controls.InputBox("SELL_PR");
				inputBox_5.placeholder = "가격(판매가)";
				inputBox_5.maxLength = 13;
				inputBox_5.inputFilter = "[0-9]";
				inputBox_5.style.css({
					"text-align" : "center"
				});
				container.addChild(inputBox_5, {
					"top": "120px",
					"left": "454px",
					"width": "142px",
					"height": "50px"
				});
				var inputBox_6 = new cpr.controls.InputBox("MEM_POINT");
				inputBox_6.placeholder = "회원 포인트 잔액";
				inputBox_6.inputFilter = "[0-9]";
				inputBox_6.style.css({
					"text-align" : "center"
				});
				container.addChild(inputBox_6, {
					"top": "330px",
					"left": "454px",
					"width": "142px",
					"height": "50px"
				});
				var output_12 = new cpr.controls.Output();
				output_12.value = "세일 여부 :";
				output_12.style.css({
					"text-align" : "center"
				});
				container.addChild(output_12, {
					"top": "50px",
					"left": "634px",
					"width": "100px",
					"height": "50px"
				});
				var output_13 = new cpr.controls.Output();
				output_13.value = "세일 가격 :";
				output_13.style.css({
					"text-align" : "center"
				});
				container.addChild(output_13, {
					"top": "120px",
					"left": "634px",
					"width": "100px",
					"height": "50px"
				});
				var output_14 = new cpr.controls.Output();
				output_14.value = "색 상 :";
				output_14.style.css({
					"text-align" : "center"
				});
				container.addChild(output_14, {
					"top": "188px",
					"left": "634px",
					"width": "100px",
					"height": "50px"
				});
				var output_15 = new cpr.controls.Output();
				output_15.value = "사이즈 :";
				output_15.style.css({
					"text-align" : "center"
				});
				container.addChild(output_15, {
					"top": "260px",
					"left": "634px",
					"width": "100px",
					"height": "50px"
				});
				var output_16 = new cpr.controls.Output();
				output_16.value = "거래처 :";
				output_16.style.css({
					"text-align" : "center"
				});
				container.addChild(output_16, {
					"top": "330px",
					"left": "634px",
					"width": "100px",
					"height": "50px"
				});
				var inputBox_7 = new cpr.controls.InputBox("SALE_PR");
				inputBox_7.readOnly = true;
				inputBox_7.placeholder = "세일 가격";
				inputBox_7.inputFilter = "[0-9]";
				inputBox_7.style.css({
					"text-align" : "center"
				});
				container.addChild(inputBox_7, {
					"top": "120px",
					"left": "733px",
					"width": "142px",
					"height": "50px"
				});
				var inputBox_8 = new cpr.controls.InputBox("COLOR");
				inputBox_8.placeholder = "색상";
				inputBox_8.style.css({
					"text-align" : "center"
				});
				container.addChild(inputBox_8, {
					"top": "188px",
					"left": "733px",
					"width": "142px",
					"height": "50px"
				});
				var inputBox_9 = new cpr.controls.InputBox("PROD_SIZE");
				inputBox_9.placeholder = "사이즈";
				inputBox_9.style.css({
					"text-align" : "center"
				});
				container.addChild(inputBox_9, {
					"top": "260px",
					"left": "733px",
					"width": "142px",
					"height": "50px"
				});
				var inputBox_10 = new cpr.controls.InputBox("PURC_PR");
				inputBox_10.placeholder = "가격(원가)";
				inputBox_10.maxLength = 13;
				inputBox_10.inputFilter = "[0-9]";
				inputBox_10.style.css({
					"text-align" : "center"
				});
				container.addChild(inputBox_10, {
					"top": "50px",
					"left": "453px",
					"width": "142px",
					"height": "50px"
				});
				var comboBox_1 = new cpr.controls.ComboBox("PROD_CLS_CD");
				comboBox_1.preventInput = true;
				(function(comboBox_1){
					comboBox_1.setItemSet(app.lookup("prodClsCd"), {
						"label": "label",
						"value": "value"
					});
				})(comboBox_1);
				container.addChild(comboBox_1, {
					"top": "198px",
					"left": "454px",
					"width": "141px",
					"height": "30px"
				});
				var checkBox_1 = new cpr.controls.CheckBox("TAXAT_TY");
				checkBox_1.value = "";
				checkBox_1.style.css({
					"text-align" : "center"
				});
				container.addChild(checkBox_1, {
					"top": "270px",
					"left": "515px",
					"width": "30px",
					"height": "30px"
				});
				var button_1 = new cpr.controls.Button("accountSrcBtn");
				button_1.value = "검색";
				if(typeof onButtonClick == "function") {
					button_1.addEventListener("click", onButtonClick);
				}
				container.addChild(button_1, {
					"top": "330px",
					"left": "885px",
					"width": "53px",
					"height": "50px"
				});
				var checkBox_2 = new cpr.controls.CheckBox("SALE_OR_NOT");
				checkBox_2.value = "";
				checkBox_2.style.css({
					"text-align" : "center"
				});
				if(typeof onCbx2ValueChange == "function") {
					checkBox_2.addEventListener("value-change", onCbx2ValueChange);
				}
				container.addChild(checkBox_2, {
					"top": "60px",
					"left": "795px",
					"width": "30px",
					"height": "30px"
				});
				var button_2 = new cpr.controls.Button();
				button_2.value = "등 록";
				button_2.style.css({
					"font-size" : "17px"
				});
				if(typeof onButtonClick2 == "function") {
					button_2.addEventListener("click", onButtonClick2);
				}
				container.addChild(button_2, {
					"top": "504px",
					"left": "451px",
					"width": "100px",
					"height": "40px"
				});
				var output_17 = new cpr.controls.Output("CLIENT_NM");
				output_17.style.css({
					"border-right-style" : "solid",
					"border-top-width" : "1px",
					"border-bottom-color" : "#bbbbbb",
					"border-right-width" : "1px",
					"padding-left" : "5px",
					"border-left-color" : "#bbbbbb",
					"border-right-color" : "#bbbbbb",
					"border-left-width" : "1px",
					"border-top-style" : "solid",
					"background-color" : "#ffffff",
					"border-left-style" : "solid",
					"border-bottom-width" : "1px",
					"border-top-color" : "#bbbbbb",
					"border-bottom-style" : "solid"
				});
				container.addChild(output_17, {
					"top": "330px",
					"left": "733px",
					"width": "142px",
					"height": "50px"
				});
			})(group_1);
			container.addChild(group_1, {
				"top": "150px",
				"left": "0px",
				"width": "1024px",
				"height": "598px"
			});
			
			var embeddedApp_1 = new cpr.controls.EmbeddedApp("ea1");
			cpr.core.App.load("PosHeader", function(app) {
				if(app){
					embeddedApp_1.app = app;
				}
			});
			container.addChild(embeddedApp_1, {
				"top": "0px",
				"left": "0px",
				"width": "1024px",
				"height": "80px"
			});
			
			var output_18 = new cpr.controls.Output("title");
			output_18.value = "상품 관리";
			output_18.style.css({
				"font-weight" : "bold",
				"font-size" : "25px",
				"text-align" : "center"
			});
			container.addChild(output_18, {
				"top": "90px",
				"left": "353px",
				"width": "318px",
				"height": "50px"
			});
			if(typeof onBodyInit == "function"){
				app.addEventListener("init", onBodyInit);
			}
		}
	});
	app.title = "PosProductRegist1";
	cpr.core.Platform.INSTANCE.register(app);
})();
