/*
 * App URI: PosHeader
 * Source Location: PosHeader.clx
 *
 * This file was generated by eXBuilder6 compiler(1.0.4807), Don't edit manually.
 */
(function() {
	var app = new cpr.core.App("PosHeader", { 
		onPrepare: function(loader) {
		},
		onCreate: function(/* cpr.core.AppInstance */ app, exports) {
			var linker = {};
			// Start - User Script
			/************************************************
			 * POSHeader.js
			 * Created at 2024. 1. 17. 오후 3:58:55.
			 *
			 * @author sunrise
			 ************************************************/


			/*
			 * "POS" 아웃풋에서 click 이벤트 발생 시 호출.
			 * 사용자가 컨트롤을 클릭할 때 발생하는 이벤트.
			 */
			function onOutputClick(e){
				var output = e.control;
				
			}

			/*
			 * "POS" 버튼에서 click 이벤트 발생 시 호출.
			 * 사용자가 컨트롤을 클릭할 때 발생하는 이벤트.
			 */
			function onButtonClick(e){
				var page = "/PosMain.do";
				window.location.href = page;
			}

			/*
			 * "판매관리" 버튼(salesManage)에서 click 이벤트 발생 시 호출.
			 * 사용자가 컨트롤을 클릭할 때 발생하는 이벤트.
			 */
			function onSalesManageClick(e){
				var page = "/POS-UI/clx-src/PosSalesManagement.clx.html";
				window.location = page;
			}

			/*
			 * "상품관리" 버튼(productManage)에서 click 이벤트 발생 시 호출.
			 * 사용자가 컨트롤을 클릭할 때 발생하는 이벤트.
			 */
			function onProductManageClick(e){
				var page = "/POS-UI/clx-src/PosProductRegist1.clx.html";
				window.location = page;
			}

			/*
			 * "시재금" 버튼(moneyCnt)에서 click 이벤트 발생 시 호출.
			 * 사용자가 컨트롤을 클릭할 때 발생하는 이벤트.
			 */
			function onMoneyCntClick(e){
				var page = "/POS-UI/clx-src/PosMoney.clx.html";
				window.location = page;
			}

			/*
			 * "회원관리" 버튼(custManage)에서 click 이벤트 발생 시 호출.
			 * 사용자가 컨트롤을 클릭할 때 발생하는 이벤트.
			 */
			function onCustManageClick(e){
				var page = "/POS-UI/clx-src/PosCust.clx.html";
				window.location = page;
			}

			/*
			 * "거래처관리" 버튼(accountManage)에서 click 이벤트 발생 시 호출.
			 * 사용자가 컨트롤을 클릭할 때 발생하는 이벤트.
			 */
			function onAccountManageClick(e){
				var page = "/POS-UI/clx-src/PosAccountManagement.clx.html";
				window.location = page;
			};
			// End - User Script
			
			// Header
			app.supportMedia("all", "header1");
			
			// Configure root container
			var container = app.getContainer();
			container.style.css({
				"width" : "100%",
				"height" : "100%"
			});
			
			// Layout
			var xYLayout_1 = new cpr.controls.layouts.XYLayout();
			container.setLayout(xYLayout_1);
			
			// UI Configuration
			var group_1 = new cpr.controls.Container();
			group_1.style.css({
				"color" : "#D6D6D6"
			});
			var xYLayout_2 = new cpr.controls.layouts.XYLayout();
			group_1.setLayout(xYLayout_2);
			(function(container){
				var group_2 = new cpr.controls.Container();
				group_2.style.css({
					"background-color" : "#BEBEBE",
					"text-align" : "center"
				});
				var xYLayout_3 = new cpr.controls.layouts.XYLayout();
				group_2.setLayout(xYLayout_3);
				(function(container){
					var output_1 = new cpr.controls.Output("sysDateTime");
					output_1.readOnly = true;
					output_1.value = "현재 날짜 시간 출력";
					if(typeof onOutputValueChange == "function") {
						output_1.addEventListener("value-change", onOutputValueChange);
					}
					container.addChild(output_1, {
						"top": "10px",
						"left": "20px",
						"width": "200px",
						"height": "60px"
					});
					var button_1 = new cpr.controls.Button("pos");
					button_1.value = "POS";
					if(typeof onButtonClick == "function") {
						button_1.addEventListener("click", onButtonClick);
					}
					container.addChild(button_1, {
						"top": "21px",
						"left": "250px",
						"width": "100px",
						"height": "38px"
					});
					var button_2 = new cpr.controls.Button("salesManage");
					button_2.value = "판매관리";
					if(typeof onSalesManageClick == "function") {
						button_2.addEventListener("click", onSalesManageClick);
					}
					container.addChild(button_2, {
						"top": "21px",
						"left": "359px",
						"width": "100px",
						"height": "38px"
					});
					var button_3 = new cpr.controls.Button("moneyCnt");
					button_3.value = "시재금";
					if(typeof onMoneyCntClick == "function") {
						button_3.addEventListener("click", onMoneyCntClick);
					}
					container.addChild(button_3, {
						"top": "21px",
						"left": "467px",
						"width": "100px",
						"height": "38px"
					});
					var button_4 = new cpr.controls.Button("productManage");
					button_4.value = "상품관리";
					if(typeof onProductManageClick == "function") {
						button_4.addEventListener("click", onProductManageClick);
					}
					container.addChild(button_4, {
						"top": "21px",
						"left": "575px",
						"width": "100px",
						"height": "38px"
					});
					var button_5 = new cpr.controls.Button("accountManage");
					button_5.value = "거래처관리";
					if(typeof onAccountManageClick == "function") {
						button_5.addEventListener("click", onAccountManageClick);
					}
					container.addChild(button_5, {
						"top": "21px",
						"left": "683px",
						"width": "100px",
						"height": "38px"
					});
					var button_6 = new cpr.controls.Button("custManage");
					button_6.value = "회원관리";
					if(typeof onCustManageClick == "function") {
						button_6.addEventListener("click", onCustManageClick);
					}
					container.addChild(button_6, {
						"top": "21px",
						"left": "791px",
						"width": "100px",
						"height": "38px"
					});
					var button_7 = new cpr.controls.Button("storeManage");
					button_7.value = "매장관리";
					container.addChild(button_7, {
						"top": "21px",
						"left": "899px",
						"width": "100px",
						"height": "38px"
					});
				})(group_2);
				container.addChild(group_2, {
					"top": "0px",
					"right": "0px",
					"left": "0px",
					"height": "80px"
				});
			})(group_1);
			container.addChild(group_1, {
				"top": "0px",
				"right": "0px",
				"bottom": "0px",
				"left": "0px"
			});
		}
	});
	app.title = "PosHeader";
	cpr.core.Platform.INSTANCE.register(app);
})();
