/*
 * App URI: PosMain
 * Source Location: PosMain.clx
 *
 * This file was generated by eXBuilder6 compiler(1.0.4807), Don't edit manually.
 */
(function() {
	var app = new cpr.core.App("PosMain", { 
		onPrepare: function(loader) {
		},
		onCreate: function(/* cpr.core.AppInstance */ app, exports) {
			var linker = {};
			// Start - User Script
			/************************************************
			 * PointOfSales.js
			 * Created at 2024. 1. 17. 오후 3:49:30.
			 *
			 * @author sunrise
			 ************************************************/;
			// End - User Script
			
			// Header
			var dataSet_1 = new cpr.data.DataSet("cashRadioBtn");
			dataSet_1.parseData({
				"columns": [
					{"name": "cash"},
					{"name": "value"}
				],
				"rows": [
					{"cash": "현금", "value": "cash"},
					{"cash": "카드", "value": "card"}
				]
			});
			app.register(dataSet_1);
			app.supportMedia("all and (min-width: 1024px)", "default");
			app.supportMedia("all and (min-width: 500px) and (max-width: 1023px)", "tablet");
			app.supportMedia("all and (max-width: 499px)", "mobile");
			
			// Configure root container
			var container = app.getContainer();
			container.overscrollBehavior = "none";
			container.style.css({
				"border-left-color" : "black",
				"border-bottom-width" : "1px",
				"border-right-color" : "black",
				"border-right-style" : "solid",
				"border-bottom-color" : "black",
				"border-top-style" : "solid",
				"border-top-color" : "black",
				"border-left-style" : "solid",
				"border-left-width" : "1px",
				"border-bottom-style" : "solid",
				"width" : "100%",
				"height" : "100%",
				"border-top-width" : "1px",
				"border-right-width" : "1px"
			});
			
			// Layout
			var xYLayout_1 = new cpr.controls.layouts.XYLayout();
			container.setLayout(xYLayout_1);
			
			// UI Configuration
			var grid_1 = new cpr.controls.Grid("grd1");
			grid_1.init({
				"columns": [
					{"width": "26px"},
					{"width": "238px"},
					{"width": "137px"},
					{"width": "70px"},
					{"width": "100px"},
					{"width": "100px"},
					{"width": "94px"},
					{"width": "106px"}
				],
				"header": {
					"rows": [{"height": "24px"}],
					"cells": [
						{
							"constraint": {"rowIndex": 0, "colIndex": 1},
							"configurator": function(cell){
								cell.text = "바코드";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 2},
							"configurator": function(cell){
								cell.text = "상품명";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 3},
							"configurator": function(cell){
								cell.text = "수량";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 4},
							"configurator": function(cell){
								cell.text = "단가";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 5},
							"configurator": function(cell){
								cell.text = "금액";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 6},
							"configurator": function(cell){
								cell.text = "할인";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 7},
							"configurator": function(cell){
								cell.text = "판매금액";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 0},
							"configurator": function(cell){
								cell.text = "";
								cell.control = (function(){
									var checkBox_1 = new cpr.controls.CheckBox("cbx1");
									return checkBox_1;
								})();
								cell.controlConstraint = {};
							}
						}
					]
				},
				"detail": {
					"rows": [{"height": "24px"}],
					"cells": [
						{
							"constraint": {"rowIndex": 0, "colIndex": 1},
							"configurator": function(cell){
								cell.columnName = "";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 2},
							"configurator": function(cell){
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 3},
							"configurator": function(cell){
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 4},
							"configurator": function(cell){
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 5},
							"configurator": function(cell){
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 6},
							"configurator": function(cell){
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 7},
							"configurator": function(cell){
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 0},
							"configurator": function(cell){
								cell.control = (function(){
									var checkBox_2 = new cpr.controls.CheckBox("cbx2");
									return checkBox_2;
								})();
								cell.controlConstraint = {};
							}
						}
					]
				}
			});
			container.addChild(grid_1, {
				"top": "120px",
				"left": "50px",
				"width": "949px",
				"height": "358px"
			});
			
			var button_1 = new cpr.controls.Button();
			button_1.value = "선택취소";
			container.addChild(button_1, {
				"top": "90px",
				"left": "760px",
				"width": "100px",
				"height": "20px"
			});
			
			var button_2 = new cpr.controls.Button();
			button_2.value = "전체취소";
			container.addChild(button_2, {
				"top": "90px",
				"left": "904px",
				"width": "95px",
				"height": "20px"
			});
			
			var radioButton_1 = new cpr.controls.RadioButton("rdb1");
			(function(radioButton_1){
				radioButton_1.setItemSet(app.lookup("cashRadioBtn"), {
					"label": "cash",
					"value": "value"
				})
			})(radioButton_1);
			container.addChild(radioButton_1, {
				"top": "516px",
				"left": "685px",
				"width": "200px",
				"height": "40px"
			});
			
			var inputBox_1 = new cpr.controls.InputBox("ipb8");
			inputBox_1.style.css({
				"border-radius" : "0px 3px 3px 0px"
			});
			container.addChild(inputBox_1, {
				"top": "565px",
				"left": "735px",
				"width": "150px",
				"height": "40px"
			});
			
			var hTMLSnippet_1 = new cpr.controls.HTMLSnippet();
			hTMLSnippet_1.value = "합계";
			hTMLSnippet_1.style.css({
				"border-radius" : "10px 0px 0px 10px",
				"background-color" : "#EDEDED",
				"vertical-align" : "middle",
				"text-align" : "center"
			});
			container.addChild(hTMLSnippet_1, {
				"top": "565px",
				"left": "645px",
				"width": "90px",
				"height": "40px"
			});
			
			var inputBox_2 = new cpr.controls.InputBox("ipb11");
			inputBox_2.style.css({
				"border-radius" : "0px 3px 3px 0px"
			});
			container.addChild(inputBox_2, {
				"top": "615px",
				"left": "735px",
				"width": "150px",
				"height": "40px"
			});
			
			var hTMLSnippet_2 = new cpr.controls.HTMLSnippet();
			hTMLSnippet_2.value = "받은 돈";
			hTMLSnippet_2.style.css({
				"border-radius" : "10px 0px 0px 10px",
				"background-color" : "#EDEDED",
				"vertical-align" : "middle",
				"text-align" : "center"
			});
			container.addChild(hTMLSnippet_2, {
				"top": "615px",
				"left": "645px",
				"width": "90px",
				"height": "40px"
			});
			
			var inputBox_3 = new cpr.controls.InputBox("ipb12");
			inputBox_3.style.css({
				"border-radius" : "0px 3px 3px 0px"
			});
			container.addChild(inputBox_3, {
				"top": "665px",
				"left": "735px",
				"width": "150px",
				"height": "40px"
			});
			
			var hTMLSnippet_3 = new cpr.controls.HTMLSnippet();
			hTMLSnippet_3.value = "거스름돈";
			hTMLSnippet_3.style.css({
				"border-radius" : "10px 0px 0px 10px",
				"background-color" : "#EDEDED",
				"vertical-align" : "middle",
				"text-align" : "center"
			});
			container.addChild(hTMLSnippet_3, {
				"top": "665px",
				"left": "645px",
				"width": "90px",
				"height": "40px"
			});
			
			var button_3 = new cpr.controls.Button();
			button_3.value = "계 산";
			container.addChild(button_3, {
				"top": "591px",
				"left": "903px",
				"width": "93px",
				"height": "83px"
			});
			
			var group_1 = new cpr.controls.Container();
			var xYLayout_2 = new cpr.controls.layouts.XYLayout();
			group_1.setLayout(xYLayout_2);
			(function(container){
				var inputBox_4 = new cpr.controls.InputBox("ipb1");
				inputBox_4.style.css({
					"border-radius" : "0px 3px 3px 0px"
				});
				container.addChild(inputBox_4, {
					"top": "41px",
					"left": "100px",
					"width": "150px",
					"height": "25px"
				});
				var inputBox_5 = new cpr.controls.InputBox("ipb2");
				inputBox_5.style.css({
					"border-radius" : "0px 3px 3px 0px"
				});
				container.addChild(inputBox_5, {
					"top": "70px",
					"left": "100px",
					"width": "150px",
					"height": "25px"
				});
				var inputBox_6 = new cpr.controls.InputBox("ipb3");
				inputBox_6.style.css({
					"border-radius" : "0px 3px 3px 0px"
				});
				container.addChild(inputBox_6, {
					"top": "99px",
					"left": "100px",
					"width": "430px",
					"height": "25px"
				});
				var inputBox_7 = new cpr.controls.InputBox("ipb4");
				inputBox_7.style.css({
					"border-radius" : "0px 3px 3px 0px"
				});
				container.addChild(inputBox_7, {
					"top": "126px",
					"left": "100px",
					"width": "150px",
					"height": "25px"
				});
				var inputBox_8 = new cpr.controls.InputBox("ipb5");
				inputBox_8.style.css({
					"border-radius" : "0px 3px 3px 0px"
				});
				container.addChild(inputBox_8, {
					"top": "155px",
					"left": "100px",
					"width": "150px",
					"height": "25px"
				});
				var inputBox_9 = new cpr.controls.InputBox("ipb6");
				inputBox_9.style.css({
					"border-radius" : "0px 3px 3px 0px"
				});
				container.addChild(inputBox_9, {
					"top": "155px",
					"left": "380px",
					"width": "150px",
					"height": "25px"
				});
				var inputBox_10 = new cpr.controls.InputBox("ipb7");
				inputBox_10.style.css({
					"border-radius" : "0px 3px 3px 0px"
				});
				container.addChild(inputBox_10, {
					"top": "126px",
					"left": "380px",
					"width": "150px",
					"height": "25px"
				});
				var inputBox_11 = new cpr.controls.InputBox("ipb9");
				inputBox_11.style.css({
					"border-radius" : "0px 3px 3px 0px"
				});
				container.addChild(inputBox_11, {
					"top": "70px",
					"left": "380px",
					"width": "150px",
					"height": "25px"
				});
				var inputBox_12 = new cpr.controls.InputBox("ipb10");
				inputBox_12.style.css({
					"border-radius" : "0px 3px 3px 0px"
				});
				container.addChild(inputBox_12, {
					"top": "41px",
					"left": "380px",
					"width": "150px",
					"height": "25px"
				});
				var button_4 = new cpr.controls.Button();
				button_4.value = "검색";
				container.addChild(button_4, {
					"top": "42px",
					"left": "540px",
					"width": "41px",
					"height": "25px"
				});
				var button_5 = new cpr.controls.Button();
				button_5.value = "회원 등록";
				container.addChild(button_5, {
					"top": "11px",
					"left": "449px",
					"width": "81px",
					"height": "20px"
				});
				var hTMLSnippet_4 = new cpr.controls.HTMLSnippet();
				hTMLSnippet_4.value = "회원 번호";
				hTMLSnippet_4.style.css({
					"background-color" : "#ededed",
					"border-radius" : "5px 0px 0px 5px",
					"background-image" : "none",
					"text-align" : "center"
				});
				container.addChild(hTMLSnippet_4, {
					"top": "41px",
					"left": "10px",
					"width": "90px",
					"height": "25px"
				});
				var hTMLSnippet_5 = new cpr.controls.HTMLSnippet();
				hTMLSnippet_5.value = "회원 이름";
				hTMLSnippet_5.style.css({
					"background-color" : "#ededed",
					"border-radius" : "5px 0px 0px 5px",
					"background-image" : "none",
					"text-align" : "center"
				});
				container.addChild(hTMLSnippet_5, {
					"top": "70px",
					"left": "10px",
					"width": "90px",
					"height": "25px"
				});
				var hTMLSnippet_6 = new cpr.controls.HTMLSnippet();
				hTMLSnippet_6.value = "주소";
				hTMLSnippet_6.style.css({
					"background-color" : "#ededed",
					"border-radius" : "5px 0px 0px 5px",
					"background-image" : "none",
					"text-align" : "center"
				});
				container.addChild(hTMLSnippet_6, {
					"top": "99px",
					"left": "10px",
					"width": "90px",
					"height": "25px"
				});
				var hTMLSnippet_7 = new cpr.controls.HTMLSnippet();
				hTMLSnippet_7.value = "총 판매액";
				hTMLSnippet_7.style.css({
					"background-color" : "#ededed",
					"border-radius" : "5px 0px 0px 5px",
					"background-image" : "none",
					"text-align" : "center"
				});
				container.addChild(hTMLSnippet_7, {
					"top": "126px",
					"left": "10px",
					"width": "90px",
					"height": "25px"
				});
				var hTMLSnippet_8 = new cpr.controls.HTMLSnippet();
				hTMLSnippet_8.value = "주민번호";
				hTMLSnippet_8.style.css({
					"background-color" : "#ededed",
					"border-radius" : "5px 0px 0px 5px",
					"background-image" : "none",
					"text-align" : "center"
				});
				container.addChild(hTMLSnippet_8, {
					"top": "155px",
					"left": "10px",
					"width": "90px",
					"height": "25px"
				});
				var hTMLSnippet_9 = new cpr.controls.HTMLSnippet();
				hTMLSnippet_9.value = "사업자 번호";
				hTMLSnippet_9.style.css({
					"background-color" : "#ededed",
					"border-radius" : "5px 0px 0px 5px",
					"background-image" : "none",
					"text-align" : "center"
				});
				container.addChild(hTMLSnippet_9, {
					"top": "155px",
					"left": "290px",
					"width": "90px",
					"height": "25px"
				});
				var hTMLSnippet_10 = new cpr.controls.HTMLSnippet();
				hTMLSnippet_10.value = "회원 포인트";
				hTMLSnippet_10.style.css({
					"background-color" : "#ededed",
					"border-radius" : "5px 0px 0px 5px",
					"background-image" : "none",
					"text-align" : "center"
				});
				container.addChild(hTMLSnippet_10, {
					"top": "126px",
					"left": "290px",
					"width": "90px",
					"height": "25px"
				});
				var hTMLSnippet_11 = new cpr.controls.HTMLSnippet();
				hTMLSnippet_11.value = "상호명";
				hTMLSnippet_11.style.css({
					"background-color" : "#ededed",
					"border-radius" : "5px 0px 0px 5px",
					"background-image" : "none",
					"text-align" : "center"
				});
				container.addChild(hTMLSnippet_11, {
					"top": "70px",
					"left": "290px",
					"width": "90px",
					"height": "25px"
				});
				var hTMLSnippet_12 = new cpr.controls.HTMLSnippet();
				hTMLSnippet_12.value = "전화번호";
				hTMLSnippet_12.style.css({
					"background-color" : "#ededed",
					"border-radius" : "5px 0px 0px 5px",
					"background-image" : "none",
					"text-align" : "center"
				});
				container.addChild(hTMLSnippet_12, {
					"top": "41px",
					"left": "290px",
					"width": "90px",
					"height": "25px"
				});
				var hTMLSnippet_13 = new cpr.controls.HTMLSnippet();
				hTMLSnippet_13.value = "고객 정보";
				hTMLSnippet_13.style.css({
					"border-right-style" : "solid",
					"border-top-width" : "1px",
					"color" : "white",
					"border-right-width" : "1px",
					"vertical-align" : "middle",
					"border-left-width" : "1px",
					"border-top-style" : "solid",
					"background-color" : "black",
					"border-radius" : "25px",
					"border-left-style" : "solid",
					"border-bottom-width" : "1px",
					"border-bottom-style" : "solid",
					"text-align" : "center"
				});
				container.addChild(hTMLSnippet_13, {
					"top": "10px",
					"left": "10px",
					"width": "100px",
					"height": "25px"
				});
			})(group_1);
			container.addChild(group_1, {
				"top": "516px",
				"left": "19px",
				"width": "590px",
				"height": "191px"
			});
			
			var embeddedApp_1 = new cpr.controls.EmbeddedApp("ea1");
			cpr.core.App.load("PosHeader", function(app) {
				if(app){
					embeddedApp_1.app = app;
				}
			});
			container.addChild(embeddedApp_1, {
				"top": "0px",
				"left": "0px",
				"width": "1024px",
				"height": "80px"
			});
		}
	});
	app.title = "PosMain";
	cpr.core.Platform.INSTANCE.register(app);
})();
