/*
 * App URI: PosMainMemberSrc
 * Source Location: PosMainMemberSrc.clx
 *
 * This file was generated by eXBuilder6 compiler(1.0.4878), Don't edit manually.
 */
(function() {
	var app = new cpr.core.App("PosMainMemberSrc", { 
		onPrepare: function(loader) {
		},
		onCreate: function(/* cpr.core.AppInstance */ app, exports) {
			var linker = {};
			// Start - User Script
			/************************************************
			 * PosMainMemberSrc.js
			 * Created at 2024. 2. 21. 오전 11:03:33.
			 *
			 * @author sunrise
			 ************************************************/;
			// End - User Script
			
			// Header
			app.supportMedia("all and (min-width: 1024px)", "default");
			app.supportMedia("all and (min-width: 500px) and (max-width: 1023px)", "tablet");
			app.supportMedia("all and (min-width: 500px) and (max-width: 499px)", "new-screen");
			app.supportMedia("all and (min-width: 500px) and (max-width: 499px)", "new-screen2");
			app.supportMedia("all and (max-width: 499px)", "mobile");
			
			// Configure root container
			var container = app.getContainer();
			container.style.css({
				"width" : "100%",
				"height" : "100%"
			});
			
			// Layout
			var xYLayout_1 = new cpr.controls.layouts.XYLayout();
			container.setLayout(xYLayout_1);
			
			// UI Configuration
			var group_1 = new cpr.controls.Container();
			var xYLayout_2 = new cpr.controls.layouts.XYLayout();
			group_1.setLayout(xYLayout_2);
			(function(container){
				var grid_1 = new cpr.controls.Grid("selectMemInfo");
				grid_1.init({
					"dataSet": app.lookup("memInfoList"),
					"columns": [
						{"width": "162px"},
						{"width": "112px"},
						{"width": "125px"}
					],
					"header": {
						"rows": [{"height": "24px"}],
						"cells": [
							{
								"constraint": {"rowIndex": 0, "colIndex": 0},
								"configurator": function(cell){
									cell.text = "회원이름";
								}
							},
							{
								"constraint": {"rowIndex": 0, "colIndex": 1},
								"configurator": function(cell){
									cell.text = "전화번호";
								}
							},
							{
								"constraint": {"rowIndex": 0, "colIndex": 2},
								"configurator": function(cell){
									cell.text = "주민 / 법인번호";
								}
							}
						]
					},
					"detail": {
						"rows": [{"height": "24px"}],
						"cells": [
							{
								"constraint": {"rowIndex": 0, "colIndex": 0},
								"configurator": function(cell){
									cell.columnName = "MEMB_NM";
								}
							},
							{
								"constraint": {"rowIndex": 0, "colIndex": 1},
								"configurator": function(cell){
									cell.columnName = "MOB_PH_NO";
									cell.control = (function(){
										var output_1 = new cpr.controls.Output();
										output_1.style.css({
											"text-align" : "center"
										});
										output_1.bind("value").toDataColumn("MOB_PH_NO");
										return output_1;
									})();
								}
							},
							{
								"constraint": {"rowIndex": 0, "colIndex": 2},
								"configurator": function(cell){
									cell.columnName = "ID_NO";
									cell.control = (function(){
										var output_2 = new cpr.controls.Output();
										output_2.format = "[0-9]{6}-[0-9]{7}";
										output_2.style.css({
											"text-align" : "center"
										});
										output_2.bind("value").toDataColumn("ID_NO");
										return output_2;
									})();
								}
							}
						]
					}
				});
				container.addChild(grid_1, {
					"top": "20px",
					"left": "20px",
					"width": "420px",
					"height": "484px"
				});
				var button_1 = new cpr.controls.Button();
				button_1.value = "확 인";
				container.addChild(button_1, {
					"top": "515px",
					"left": "195px",
					"width": "70px",
					"height": "25px"
				});
			})(group_1);
			container.addChild(group_1, {
				"top": "30px",
				"left": "10px",
				"width": "460px",
				"height": "560px"
			});
			
			var output_3 = new cpr.controls.Output("PH_NO");
			output_3.value = "";
			container.addChild(output_3, {
				"top": "10px",
				"left": "24px",
				"width": "100px",
				"height": "20px"
			});
		}
	});
	app.title = "PosMainMemberSrc";
	cpr.core.Platform.INSTANCE.register(app);
})();
