/*
 * App URI: PosMoney
 * Source Location: PosMoney.clx
 *
 * This file was generated by eXBuilder6 compiler(1.0.4878), Don't edit manually.
 */
(function() {
	var app = new cpr.core.App("PosMoney", { 
		onPrepare: function(loader) {
		},
		onCreate: function(/* cpr.core.AppInstance */ app, exports) {
			var linker = {};
			// Start - User Script
			/************************************************
			 * PosMoney.js
			 * Created at 2024. 1. 22. 오전 12:48:06.
			 *
			 * @author PC2
			 ************************************************/

			/*
			 * "입금하기" 버튼에서 click 이벤트 발생 시 호출.
			 * 사용자가 컨트롤을 클릭할 때 발생하는 이벤트.
			 */
			function onButtonClick(e){
				var content1 = app.lookup("content1").value;
				var money1 = app.lookup("money1").value;
				
				if(money1 == ''){
					alert('금액을 작성해 주세요.');
					return false;
				}
				if(content1 == ''){
					alert('내용을 작성해 주세요.');
					return false;
				}else{
					var totCnt = Number(app.lookup("totalCnt").value);
					var money1 = Number(app.lookup("money1").value);
					
					var submission = new cpr.protocols.Submission();
					submission.action = '/POS/vaultCashInOut.do';
					submission.responseType = 'javascript';
			//		submission.async = false;
					submission.setParameters("TER_SER_NO", '1');
					submission.setParameters("DEP_PAY_TY", '1');
					submission.setParameters("CONTENTS", content1);
					submission.setParameters("AMT", money1);
					
					submission.addEventListener("submit-success", function(e){
						var submi = e.control;
						console.log(submi.xhr.responseText);
						onBodyLoad();
						alert('입금이 완료되었습니다.');
						debugger;
					});
					submission.send();
					
			//		app.lookup("totalCnt").value = (totCnt + money1).toString();
					app.lookup("money1").value = '';
					app.lookup("content1").value = '';
				}
				
				
			}

			/*
			 * "출금하기" 버튼에서 click 이벤트 발생 시 호출.
			 * 사용자가 컨트롤을 클릭할 때 발생하는 이벤트.
			 */
			function onButtonClick2(e){
				var content2 = app.lookup("content2").value;
				var totcnt = app.lookup("totalCnt").value;
				var money2 = app.lookup("money2").value;
				
				if(money2 == ''){
					alert('금액을 작성해 주세요.');
					return false;
				}
				if(content2 == ''){
					alert('내용을 작성해 주세요.');
					return false;
				}
			//	if(totcnt < money2){
			//		alert('잔액이 부족합니다.');
			//		return false;
			//	}
				else{
					var totCnt = Number(app.lookup("totalCnt").value);
					var money2 = Number(app.lookup("money2").value);
					
					var submission = new cpr.protocols.Submission();
					submission.action = '/POS/vaultCashInOut.do';
					submission.responseType = 'javascript';
			//		submission.async = false;
					submission.setParameters("TER_SER_NO", '1');
					submission.setParameters("DEP_PAY_TY", '2');
					submission.setParameters("CONTENTS", content2);
					submission.setParameters("AMT", money2);
					
					submission.addEventListener("submit-success", function(e){
						var submi = e.control;
						console.log(submi.xhr.responseText);
						var jsonObj = JSON.parse(submi.xhr.responseText);
						onBodyLoad();
						alert('출금이 완료되었습니다.');
						debugger;
					});
					submission.send();
			//		app.lookup("totalCnt").value = (totCnt - money2).toString();
					app.lookup("money2").value = '';
					app.lookup("content2").value = '';
				}
			}

			/*
			 * 루트 컨테이너에서 load 이벤트 발생 시 호출.
			 * 앱이 최초 구성된후 최초 랜더링 직후에 발생하는 이벤트 입니다.
			 */
			function onBodyLoad(e){
				
				var submission = new cpr.protocols.Submission();
				submission.action = '/POS/vaultInit.do';
				submission.responseType = 'javascript';
			//	submission.async = false;
				submission.addEventListener("receive", function(e){
					var submi = e.control;
					
					console.log(submi.xhr.responseText);
					var jsonObj = JSON.parse(submi.xhr.responseText);
					var totCash = jsonObj['totCash'];
					app.lookup("totalCnt").value = totCash;
					
					
				});
				submission.send();
				
			};
			// End - User Script
			
			// Header
			app.supportMedia("all", "default");
			
			// Configure root container
			var container = app.getContainer();
			container.style.css({
				"width" : "100%",
				"height" : "100%"
			});
			
			// Layout
			var xYLayout_1 = new cpr.controls.layouts.XYLayout();
			container.setLayout(xYLayout_1);
			
			// UI Configuration
			var embeddedApp_1 = new cpr.controls.EmbeddedApp("ea1");
			cpr.core.App.load("PosHeader", function(app) {
				if(app){
					embeddedApp_1.app = app;
				}
			});
			container.addChild(embeddedApp_1, {
				"top": "0px",
				"left": "0px",
				"width": "1024px",
				"height": "80px"
			});
			
			var group_1 = new cpr.controls.Container();
			group_1.style.css({
				"background-color" : "#E0E0E0"
			});
			var xYLayout_2 = new cpr.controls.layouts.XYLayout();
			group_1.setLayout(xYLayout_2);
			(function(container){
				var output_1 = new cpr.controls.Output();
				output_1.value = "최종 잔액";
				output_1.style.css({
					"background-color" : "#BEBEBE",
					"border-radius" : "35px 35px 35px 35px",
					"font-weight" : "bold",
					"font-size" : "16px",
					"text-align" : "center"
				});
				container.addChild(output_1, {
					"top": "413px",
					"left": "334px",
					"width": "140px",
					"height": "40px"
				});
				var output_2 = new cpr.controls.Output("totalCnt");
				output_2.dataType = "number";
				output_2.format = "s#,##0";
				output_2.displayExp = "text + '원'";
				output_2.style.css({
					"font-weight" : "bold",
					"font-size" : "18px",
					"text-align" : "center"
				});
				container.addChild(output_2, {
					"top": "413px",
					"left": "527px",
					"width": "182px",
					"height": "40px"
				});
				var group_2 = new cpr.controls.Container();
				group_2.style.css({
					"border-bottom-color" : "#c7c7c7",
					"border-bottom-width" : "4px",
					"border-bottom-style" : "solid"
				});
				var xYLayout_3 = new cpr.controls.layouts.XYLayout();
				group_2.setLayout(xYLayout_3);
				(function(container){
					var output_3 = new cpr.controls.Output();
					output_3.value = "입 금";
					output_3.style.css({
						"background-color" : "#BEBEBE",
						"border-radius" : "40px 40px 40px 40px",
						"font-weight" : "bold",
						"font-size" : "20px",
						"text-align" : "center"
					});
					container.addChild(output_3, {
						"top": "38px",
						"left": "41px",
						"width": "140px",
						"height": "110px"
					});
					var inputBox_1 = new cpr.controls.InputBox("content1");
					inputBox_1.placeholder = "내용을 입력해 주세요.";
					inputBox_1.style.css({
						"border-radius" : "5px 5px 5px 5px",
						"text-align" : "right"
					});
					container.addChild(inputBox_1, {
						"top": "100px",
						"left": "191px",
						"width": "294px",
						"height": "48px"
					});
					var button_1 = new cpr.controls.Button();
					button_1.value = "입금하기";
					button_1.style.css({
						"font-size" : "17px"
					});
					if(typeof onButtonClick == "function") {
						button_1.addEventListener("click", onButtonClick);
					}
					container.addChild(button_1, {
						"top": "73px",
						"left": "508px",
						"width": "100px",
						"height": "40px"
					});
					var output_4 = new cpr.controls.Output();
					output_4.value = "출 금";
					output_4.style.css({
						"background-color" : "#BEBEBE",
						"border-radius" : "40px 40px 40px 40px",
						"font-weight" : "bold",
						"font-size" : "20px",
						"text-align" : "center"
					});
					container.addChild(output_4, {
						"top": "176px",
						"left": "41px",
						"width": "140px",
						"height": "110px"
					});
					var inputBox_2 = new cpr.controls.InputBox("content2");
					inputBox_2.placeholder = "내용을 입력해 주세요.";
					inputBox_2.style.css({
						"border-radius" : "5px 5px 5px 5px",
						"text-align" : "right"
					});
					container.addChild(inputBox_2, {
						"top": "238px",
						"left": "191px",
						"width": "294px",
						"height": "48px"
					});
					var button_2 = new cpr.controls.Button();
					button_2.value = "출금하기";
					button_2.style.css({
						"font-size" : "17px"
					});
					if(typeof onButtonClick2 == "function") {
						button_2.addEventListener("click", onButtonClick2);
					}
					container.addChild(button_2, {
						"top": "211px",
						"left": "508px",
						"width": "100px",
						"height": "40px"
					});
					var numberEditor_1 = new cpr.controls.NumberEditor("money1");
					numberEditor_1.min = new cpr.foundation.DecimalType("100");
					numberEditor_1.spinButton = false;
					numberEditor_1.placeholder = "금액을 입력해 주세요.";
					numberEditor_1.displayExp = "text + '원'";
					numberEditor_1.style.css({
						"border-radius" : "5px 5px 5px 5px",
						"text-align" : "right"
					});
					container.addChild(numberEditor_1, {
						"top": "38px",
						"left": "191px",
						"width": "294px",
						"height": "48px"
					});
					var numberEditor_2 = new cpr.controls.NumberEditor("money2");
					numberEditor_2.spinButton = false;
					numberEditor_2.placeholder = "금액을 입력해 주세요.";
					numberEditor_2.displayExp = "text + '원'";
					numberEditor_2.style.css({
						"border-radius" : "5px 5px 5px 5px",
						"text-align" : "right"
					});
					container.addChild(numberEditor_2, {
						"top": "176px",
						"left": "191px",
						"width": "294px",
						"height": "48px"
					});
				})(group_2);
				container.addChild(group_2, {
					"top": "64px",
					"left": "195px",
					"width": "628px",
					"height": "320px"
				});
			})(group_1);
			container.addChild(group_1, {
				"top": "150px",
				"left": "0px",
				"width": "1024px",
				"height": "598px"
			});
			
			var output_5 = new cpr.controls.Output("title");
			output_5.value = "시재금";
			output_5.style.css({
				"font-weight" : "bold",
				"font-size" : "25px",
				"text-align" : "center"
			});
			container.addChild(output_5, {
				"top": "90px",
				"left": "353px",
				"width": "318px",
				"height": "50px"
			});
			if(typeof onBodyLoad == "function"){
				app.addEventListener("load", onBodyLoad);
			}
		}
	});
	app.title = "PosMoney";
	cpr.core.Platform.INSTANCE.register(app);
})();
