/*
 * App URI: PosSalesManagement
 * Source Location: PosSalesManagement.clx
 *
 * This file was generated by eXBuilder6 compiler(1.0.4807), Don't edit manually.
 */
(function() {
	var app = new cpr.core.App("PosSalesManagement", { 
		onPrepare: function(loader) {
		},
		onCreate: function(/* cpr.core.AppInstance */ app, exports) {
			var linker = {};
			// Start - User Script
			/************************************************
			 * POSSalesManagement.js
			 * Created at 2024. 1. 19. 오후 2:17:29.
			 *
			 * @author sunrise
			 ************************************************/;
			// End - User Script
			
			// Header
			var dataSet_1 = new cpr.data.DataSet("판매구분");
			dataSet_1.parseData({
				"columns": [
					{"name": "label"},
					{"name": "value"}
				],
				"rows": [
					{"label": "육류", "value": "meat"},
					{"label": "쌀", "value": "meal"},
					{"label": "음료", "value": "drink"}
				]
			});
			app.register(dataSet_1);
			
			var dataSet_2 = new cpr.data.DataSet("ds1");
			dataSet_2.parseData({
				"columns": [
					{"name": "바코드"},
					{"name": "상품명"},
					{"name": "단가"},
					{"name": "수량"},
					{"name": "할인"},
					{"name": "부가세"},
					{"name": "합계"},
					{"name": "포인트"}
				],
				"rows": [
					{"바코드": "1", "상품명": "1", "단가": "1", "수량": "1", "할인": "1", "부가세": "1", "합계": "1", "포인트": "1"},
					{"바코드": "바코드2", "상품명": "상품명2", "단가": "단가2", "수량": "수량2", "할인": "할인2", "부가세": "부가세2", "합계": "합계2", "포인트": "포인트2"},
					{"바코드": "바코드3", "상품명": "상품명3", "단가": "단가3", "수량": "수량3", "할인": "할인3", "부가세": "부가세3", "합계": "합계3", "포인트": "포인트3"}
				]
			});
			app.register(dataSet_2);
			app.supportMedia("all and (min-width: 1024px)", "default");
			app.supportMedia("all and (min-width: 500px) and (max-width: 1023px)", "tablet");
			app.supportMedia("all and (max-width: 499px)", "mobile");
			
			// Configure root container
			var container = app.getContainer();
			container.style.css({
				"width" : "100%",
				"height" : "100%"
			});
			
			// Layout
			var xYLayout_1 = new cpr.controls.layouts.XYLayout();
			container.setLayout(xYLayout_1);
			
			// UI Configuration
			var hTMLSnippet_1 = new cpr.controls.HTMLSnippet();
			hTMLSnippet_1.value = "전표 내역";
			hTMLSnippet_1.style.css({
				"border-right-style" : "solid",
				"border-top-width" : "1px",
				"color" : "white",
				"border-right-width" : "1px",
				"vertical-align" : "middle",
				"border-left-width" : "1px",
				"border-top-style" : "solid",
				"background-color" : "black",
				"border-radius" : "25px",
				"border-left-style" : "solid",
				"border-bottom-width" : "1px",
				"border-bottom-style" : "solid",
				"text-align" : "center"
			});
			container.addChild(hTMLSnippet_1, {
				"top": "150px",
				"left": "20px",
				"width": "100px",
				"height": "25px"
			});
			
			var hTMLSnippet_2 = new cpr.controls.HTMLSnippet();
			hTMLSnippet_2.value = "상품 내역";
			hTMLSnippet_2.style.css({
				"border-right-style" : "solid",
				"border-top-width" : "1px",
				"color" : "white",
				"border-right-width" : "1px",
				"vertical-align" : "middle",
				"border-left-width" : "1px",
				"border-top-style" : "solid",
				"background-color" : "black",
				"border-radius" : "25px",
				"border-left-style" : "solid",
				"border-bottom-width" : "1px",
				"border-bottom-style" : "solid",
				"text-align" : "center"
			});
			container.addChild(hTMLSnippet_2, {
				"top": "550px",
				"left": "20px",
				"width": "100px",
				"height": "25px"
			});
			
			var grid_1 = new cpr.controls.Grid("grd1");
			grid_1.init({
				"columns": [
					{"width": "27px"},
					{"width": "122px"},
					{"width": "118px"},
					{"width": "78px"},
					{"width": "105px"},
					{"width": "76px"},
					{"width": "151px"}
				],
				"header": {
					"rows": [{"height": "46px"}],
					"cells": [
						{
							"constraint": {"rowIndex": 0, "colIndex": 1},
							"configurator": function(cell){
								cell.text = "판매\r\n일련번호";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 2},
							"configurator": function(cell){
								cell.text = "회원번호";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 3},
							"configurator": function(cell){
								cell.text = "회원구분";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 4},
							"configurator": function(cell){
								cell.text = "합계";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 5},
							"configurator": function(cell){
								cell.text = "판매구분";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 0},
							"configurator": function(cell){
								cell.style.css({
									"vertical-align" : "middle"
								});
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 6},
							"configurator": function(cell){
								cell.text = "거래시간";
							}
						}
					]
				},
				"detail": {
					"rows": [{"height": "24px"}],
					"cells": [
						{
							"constraint": {"rowIndex": 0, "colIndex": 1},
							"configurator": function(cell){
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 2},
							"configurator": function(cell){
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 3},
							"configurator": function(cell){
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 4},
							"configurator": function(cell){
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 5},
							"configurator": function(cell){
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 0},
							"configurator": function(cell){
								cell.control = (function(){
									var radioButton_1 = new cpr.controls.RadioButton("rdb2");
									return radioButton_1;
								})();
								cell.controlConstraint = {};
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 6},
							"configurator": function(cell){
							}
						}
					]
				}
			});
			container.addChild(grid_1, {
				"top": "190px",
				"left": "20px",
				"width": "719px",
				"height": "351px"
			});
			
			var group_1 = new cpr.controls.Container();
			group_1.style.css({
				"background-color" : "#E0E0E0"
			});
			var xYLayout_2 = new cpr.controls.layouts.XYLayout();
			group_1.setLayout(xYLayout_2);
			(function(container){
				var comboBox_1 = new cpr.controls.ComboBox("cmb1");
				comboBox_1.preventInput = true;
				(function(comboBox_1){
					comboBox_1.setItemSet(app.lookup("판매구분"), {
						"label": "label",
						"value": "value"
					});
				})(comboBox_1);
				container.addChild(comboBox_1, {
					"top": "10px",
					"left": "19px",
					"width": "100px",
					"height": "25px"
				});
				var inputBox_1 = new cpr.controls.InputBox("ipb1");
				inputBox_1.placeholder = "전화번호";
				container.addChild(inputBox_1, {
					"top": "10px",
					"left": "140px",
					"width": "112px",
					"height": "25px"
				});
				var inputBox_2 = new cpr.controls.InputBox("ipb2");
				inputBox_2.placeholder = "바코드 번호";
				container.addChild(inputBox_2, {
					"top": "10px",
					"left": "263px",
					"width": "130px",
					"height": "25px"
				});
				var dateInput_1 = new cpr.controls.DateInput("dti1");
				dateInput_1.value = "";
				dateInput_1.placeholder = "YYYY-MM-DD HH:mm";
				dateInput_1.mask = "YYYY-MM-DD HH:mm";
				dateInput_1.format = "YYYYMMDDHHmm";
				container.addChild(dateInput_1, {
					"top": "10px",
					"left": "403px",
					"width": "199px",
					"height": "25px"
				});
				var output_1 = new cpr.controls.Output();
				output_1.value = "~";
				output_1.style.css({
					"text-align" : "center"
				});
				container.addChild(output_1, {
					"top": "10px",
					"left": "612px",
					"width": "25px",
					"height": "25px"
				});
				var dateInput_2 = new cpr.controls.DateInput("dti3");
				dateInput_2.value = "";
				dateInput_2.placeholder = "YYYY-MM-DD HH:mm";
				dateInput_2.mask = "YYYY-MM-DD HH:mm";
				dateInput_2.format = "YYYYMMDDHHmm";
				container.addChild(dateInput_2, {
					"top": "10px",
					"left": "647px",
					"width": "199px",
					"height": "25px"
				});
				var button_1 = new cpr.controls.Button();
				button_1.value = "조회";
				container.addChild(button_1, {
					"top": "10px",
					"left": "905px",
					"width": "56px",
					"height": "25px"
				});
			})(group_1);
			container.addChild(group_1, {
				"top": "90px",
				"left": "20px",
				"width": "982px",
				"height": "50px"
			});
			
			var grid_2 = new cpr.controls.Grid("grd2");
			grid_2.init({
				"dataSet": app.lookup("ds1"),
				"columns": [
					{"width": "26px"},
					{"width": "100px"},
					{"width": "100px"},
					{"width": "100px"},
					{"width": "100px"},
					{"width": "100px"},
					{"width": "100px"},
					{"width": "100px"},
					{"width": "100px"}
				],
				"header": {
					"rows": [{"height": "24px"}],
					"cells": [
						{
							"constraint": {"rowIndex": 0, "colIndex": 1},
							"configurator": function(cell){
								cell.filterable = false;
								cell.sortable = false;
								cell.targetColumnName = "바코드";
								cell.text = "바코드";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 2},
							"configurator": function(cell){
								cell.filterable = false;
								cell.sortable = false;
								cell.targetColumnName = "상품명";
								cell.text = "상품명";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 3},
							"configurator": function(cell){
								cell.filterable = false;
								cell.sortable = false;
								cell.targetColumnName = "단가";
								cell.text = "단가";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 4},
							"configurator": function(cell){
								cell.filterable = false;
								cell.sortable = false;
								cell.targetColumnName = "수량";
								cell.text = "수량";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 5},
							"configurator": function(cell){
								cell.filterable = false;
								cell.sortable = false;
								cell.targetColumnName = "할인";
								cell.text = "할인";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 6},
							"configurator": function(cell){
								cell.filterable = false;
								cell.sortable = false;
								cell.targetColumnName = "부가세";
								cell.text = "부가세";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 7},
							"configurator": function(cell){
								cell.filterable = false;
								cell.sortable = false;
								cell.targetColumnName = "합계";
								cell.text = "합계";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 8},
							"configurator": function(cell){
								cell.filterable = false;
								cell.sortable = false;
								cell.targetColumnName = "포인트";
								cell.text = "포인트";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 0},
							"configurator": function(cell){
								cell.text = "";
								cell.control = (function(){
									var checkBoxGroup_1 = new cpr.controls.CheckBoxGroup("cbg1");
									return checkBoxGroup_1;
								})();
								cell.controlConstraint = {};
							}
						}
					]
				},
				"detail": {
					"rows": [{"height": "30px"}],
					"cells": [
						{
							"constraint": {"rowIndex": 0, "colIndex": 1},
							"configurator": function(cell){
								cell.columnName = "바코드";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 2},
							"configurator": function(cell){
								cell.columnName = "상품명";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 3},
							"configurator": function(cell){
								cell.columnName = "단가";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 4},
							"configurator": function(cell){
								cell.columnName = "수량";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 5},
							"configurator": function(cell){
								cell.columnName = "할인";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 6},
							"configurator": function(cell){
								cell.columnName = "부가세";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 7},
							"configurator": function(cell){
								cell.columnName = "합계";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 8},
							"configurator": function(cell){
								cell.columnName = "포인트";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 0},
							"configurator": function(cell){
								cell.control = (function(){
									var checkBox_1 = new cpr.controls.CheckBox("cbx1");
									return checkBox_1;
								})();
								cell.controlConstraint = {"width": 25};
							}
						}
					]
				}
			});
			container.addChild(grid_2, {
				"top": "585px",
				"left": "20px",
				"width": "981px",
				"height": "161px"
			});
			
			var group_2 = new cpr.controls.Container();
			var xYLayout_3 = new cpr.controls.layouts.XYLayout();
			group_2.setLayout(xYLayout_3);
			(function(container){
				var hTMLSnippet_3 = new cpr.controls.HTMLSnippet();
				hTMLSnippet_3.value = "판매 금액";
				hTMLSnippet_3.style.css({
					"border-right-style" : "solid",
					"border-top-width" : "1px",
					"color" : "white",
					"border-right-width" : "1px",
					"vertical-align" : "middle",
					"border-left-width" : "1px",
					"border-top-style" : "solid",
					"background-color" : "black",
					"border-radius" : "25px",
					"border-left-style" : "solid",
					"border-bottom-width" : "1px",
					"border-bottom-style" : "solid",
					"text-align" : "center"
				});
				container.addChild(hTMLSnippet_3, {
					"top": "7px",
					"left": "9px",
					"width": "100px",
					"height": "25px"
				});
				var output_2 = new cpr.controls.Output();
				output_2.value = "구분";
				output_2.style.css({
					"border-right-style" : "solid",
					"border-top-width" : "1px",
					"border-bottom-color" : "#cccccc",
					"border-right-width" : "1px",
					"vertical-align" : "middle",
					"border-left-color" : "#cccccc",
					"border-right-color" : "#cccccc",
					"border-left-width" : "1px",
					"border-top-style" : "solid",
					"background-color" : "#ededed",
					"border-radius" : "10px 0px 0px 0px",
					"border-left-style" : "solid",
					"border-bottom-width" : "1px",
					"border-top-color" : "#cccccc",
					"border-bottom-style" : "solid",
					"background-image" : "none",
					"text-align" : "center"
				});
				container.addChild(output_2, {
					"top": "46px",
					"left": "9px",
					"width": "70px",
					"height": "55px"
				});
				var output_3 = new cpr.controls.Output();
				output_3.value = "전체";
				output_3.style.css({
					"border-right-style" : "solid",
					"border-top-width" : "1px",
					"border-bottom-color" : "#cccccc",
					"border-right-width" : "1px",
					"vertical-align" : "middle",
					"border-left-color" : "#cccccc",
					"border-right-color" : "#cccccc",
					"border-left-width" : "1px",
					"border-top-style" : "solid",
					"background-color" : "#ededed",
					"border-radius" : "0px 0px 0px 0px",
					"border-left-style" : "solid",
					"border-bottom-width" : "1px",
					"border-top-color" : "#cccccc",
					"border-bottom-style" : "solid",
					"background-image" : "none",
					"text-align" : "center"
				});
				container.addChild(output_3, {
					"top": "100px",
					"left": "9px",
					"width": "70px",
					"height": "60px"
				});
				var output_4 = new cpr.controls.Output();
				output_4.value = "현금";
				output_4.style.css({
					"border-right-style" : "solid",
					"border-top-width" : "1px",
					"border-bottom-color" : "#cccccc",
					"border-right-width" : "1px",
					"vertical-align" : "middle",
					"border-left-color" : "#cccccc",
					"border-right-color" : "#cccccc",
					"border-left-width" : "1px",
					"border-top-style" : "solid",
					"background-color" : "#ededed",
					"border-radius" : "0px 0px 0px 0px",
					"border-left-style" : "solid",
					"border-bottom-width" : "1px",
					"border-top-color" : "#cccccc",
					"border-bottom-style" : "solid",
					"background-image" : "none",
					"text-align" : "center"
				});
				container.addChild(output_4, {
					"top": "159px",
					"left": "9px",
					"width": "70px",
					"height": "60px"
				});
				var output_5 = new cpr.controls.Output();
				output_5.value = "카드";
				output_5.style.css({
					"border-right-style" : "solid",
					"border-top-width" : "1px",
					"border-bottom-color" : "#cccccc",
					"border-right-width" : "1px",
					"vertical-align" : "middle",
					"border-left-color" : "#cccccc",
					"border-right-color" : "#cccccc",
					"border-left-width" : "1px",
					"border-top-style" : "solid",
					"background-color" : "#ededed",
					"border-radius" : "0px 0px 0px 0px",
					"border-left-style" : "solid",
					"border-bottom-width" : "1px",
					"border-top-color" : "#cccccc",
					"border-bottom-style" : "solid",
					"background-image" : "none",
					"text-align" : "center"
				});
				container.addChild(output_5, {
					"top": "277px",
					"left": "9px",
					"width": "70px",
					"height": "60px"
				});
				var output_6 = new cpr.controls.Output();
				output_6.value = "상품권";
				output_6.style.css({
					"border-right-style" : "solid",
					"border-top-width" : "1px",
					"border-bottom-color" : "#cccccc",
					"border-right-width" : "1px",
					"vertical-align" : "middle",
					"border-left-color" : "#cccccc",
					"border-right-color" : "#cccccc",
					"border-left-width" : "1px",
					"border-top-style" : "solid",
					"background-color" : "#ededed",
					"border-radius" : "0px 0px 0px 0px",
					"border-left-style" : "solid",
					"border-bottom-width" : "1px",
					"border-top-color" : "#cccccc",
					"border-bottom-style" : "solid",
					"background-image" : "none",
					"text-align" : "center"
				});
				container.addChild(output_6, {
					"top": "218px",
					"left": "9px",
					"width": "70px",
					"height": "60px"
				});
				var output_7 = new cpr.controls.Output();
				output_7.value = "포인트";
				output_7.style.css({
					"border-right-style" : "solid",
					"border-top-width" : "1px",
					"border-bottom-color" : "#cccccc",
					"border-right-width" : "1px",
					"vertical-align" : "middle",
					"border-left-color" : "#cccccc",
					"border-right-color" : "#cccccc",
					"border-left-width" : "1px",
					"border-top-style" : "solid",
					"background-color" : "#ededed",
					"border-radius" : "0px 0px 0px 10px",
					"border-left-style" : "solid",
					"border-bottom-width" : "1px",
					"border-top-color" : "#cccccc",
					"border-bottom-style" : "solid",
					"background-image" : "none",
					"text-align" : "center"
				});
				container.addChild(output_7, {
					"top": "336px",
					"left": "9px",
					"width": "70px",
					"height": "60px"
				});
				var output_8 = new cpr.controls.Output();
				output_8.value = "합계";
				output_8.style.css({
					"border-right-style" : "solid",
					"border-top-width" : "1px",
					"border-bottom-color" : "#cccccc",
					"border-right-width" : "1px",
					"border-left-color" : "#cccccc",
					"border-right-color" : "#cccccc",
					"border-left-width" : "1px",
					"border-top-style" : "solid",
					"background-color" : "#ededed",
					"border-left-style" : "solid",
					"border-bottom-width" : "1px",
					"border-top-color" : "#cccccc",
					"border-bottom-style" : "solid",
					"background-image" : "none",
					"text-align" : "center"
				});
				container.addChild(output_8, {
					"top": "46px",
					"left": "78px",
					"width": "130px",
					"height": "55px"
				});
				var output_9 = new cpr.controls.Output();
				output_9.value = "Output";
				output_9.style.css({
					"border-right-style" : "solid",
					"border-top-width" : "1px",
					"border-bottom-color" : "#cccccc",
					"border-right-width" : "1px",
					"border-left-color" : "#cccccc",
					"border-right-color" : "#cccccc",
					"border-left-width" : "1px",
					"border-top-style" : "solid",
					"border-left-style" : "solid",
					"border-bottom-width" : "1px",
					"border-top-color" : "#cccccc",
					"border-bottom-style" : "solid",
					"text-align" : "center"
				});
				container.addChild(output_9, {
					"top": "100px",
					"left": "78px",
					"width": "130px",
					"height": "60px"
				});
				var output_10 = new cpr.controls.Output();
				output_10.value = "Output";
				output_10.style.css({
					"border-right-style" : "solid",
					"border-top-width" : "1px",
					"border-bottom-color" : "#cccccc",
					"border-right-width" : "1px",
					"border-left-color" : "#cccccc",
					"border-right-color" : "#cccccc",
					"border-left-width" : "1px",
					"border-top-style" : "solid",
					"border-left-style" : "solid",
					"border-bottom-width" : "1px",
					"border-top-color" : "#cccccc",
					"border-bottom-style" : "solid",
					"text-align" : "center"
				});
				container.addChild(output_10, {
					"top": "159px",
					"left": "78px",
					"width": "130px",
					"height": "60px"
				});
				var output_11 = new cpr.controls.Output();
				output_11.value = "Output";
				output_11.style.css({
					"border-right-style" : "solid",
					"border-top-width" : "1px",
					"border-bottom-color" : "#cccccc",
					"border-right-width" : "1px",
					"border-left-color" : "#cccccc",
					"border-right-color" : "#cccccc",
					"border-left-width" : "1px",
					"border-top-style" : "solid",
					"border-left-style" : "solid",
					"border-bottom-width" : "1px",
					"border-top-color" : "#cccccc",
					"border-bottom-style" : "solid",
					"text-align" : "center"
				});
				container.addChild(output_11, {
					"top": "218px",
					"left": "78px",
					"width": "130px",
					"height": "60px"
				});
				var output_12 = new cpr.controls.Output();
				output_12.value = "Output";
				output_12.style.css({
					"border-right-style" : "solid",
					"border-top-width" : "1px",
					"border-bottom-color" : "#cccccc",
					"border-right-width" : "1px",
					"border-left-color" : "#cccccc",
					"border-right-color" : "#cccccc",
					"border-left-width" : "1px",
					"border-top-style" : "solid",
					"border-left-style" : "solid",
					"border-bottom-width" : "1px",
					"border-top-color" : "#cccccc",
					"border-bottom-style" : "solid",
					"text-align" : "center"
				});
				container.addChild(output_12, {
					"top": "277px",
					"left": "78px",
					"width": "130px",
					"height": "60px"
				});
				var output_13 = new cpr.controls.Output();
				output_13.value = "Output";
				output_13.style.css({
					"border-right-style" : "solid",
					"border-top-width" : "1px",
					"border-bottom-color" : "#cccccc",
					"border-right-width" : "1px",
					"border-left-color" : "#cccccc",
					"border-right-color" : "#cccccc",
					"border-left-width" : "1px",
					"border-top-style" : "solid",
					"border-left-style" : "solid",
					"border-bottom-width" : "1px",
					"border-top-color" : "#cccccc",
					"border-bottom-style" : "solid",
					"text-align" : "center"
				});
				container.addChild(output_13, {
					"top": "336px",
					"left": "78px",
					"width": "130px",
					"height": "60px"
				});
			})(group_2);
			container.addChild(group_2, {
				"top": "139px",
				"left": "785px",
				"width": "217px",
				"height": "405px"
			});
			
			var button_2 = new cpr.controls.Button();
			button_2.value = "선택취소";
			container.addChild(button_2, {
				"top": "555px",
				"left": "728px",
				"width": "100px",
				"height": "20px"
			});
			
			var button_3 = new cpr.controls.Button();
			button_3.value = "전체취소";
			container.addChild(button_3, {
				"top": "555px",
				"left": "872px",
				"width": "95px",
				"height": "20px"
			});
			
			var embeddedApp_1 = new cpr.controls.EmbeddedApp("ea1");
			cpr.core.App.load("PosHeader", function(app) {
				if(app){
					embeddedApp_1.app = app;
				}
			});
			container.addChild(embeddedApp_1, {
				"top": "0px",
				"left": "0px",
				"width": "1024px",
				"height": "80px"
			});
		}
	});
	app.title = "PosSalesManagement";
	cpr.core.Platform.INSTANCE.register(app);
})();
