-- 판매 테이블 O
CREATE TABLE SALES_TBL (
    SALES_DT        VARCHAR2(8)     NOT NULL, /* PK */
	SALES_SER_NO    VARCHAR2(4)     NOT NULL, /* PK */
    TER_NO          VARCHAR2(8)     NOT NULL,
    TRANS_DT        VARCHAR2(8)     NOT NULL,
    TRANS_TM        VARCHAR2(8)     NOT NULL,
    MEMB_TY         VARCHAR2(1)     NOT NULL, /* 등록회원 = 1, 미등록회원 = 2 */
    MEMB_SER_NO     VARCHAR2(6)     NOT NULL,
    CANC_TY         VARCHAR2(1)     NOT NULL, /* 전체취소 = 1 */
    
    CONSTRAINT SALES_TBL_PK PRIMARY KEY(SALES_DT, SALES_SER_NO)
);

COMMENT ON TABLE SALES_TBL IS '판매';
COMMENT ON COLUMN SALES_TBL.SALES_DT IS '판매일자';
COMMENT ON COLUMN SALES_TBL.SALES_SER_NO IS '판매일련번호';
COMMENT ON COLUMN SALES_TBL.TER_NO IS '단말기번호';
COMMENT ON COLUMN SALES_TBL.TRANS_DT IS '거래일자';
COMMENT ON COLUMN SALES_TBL.TRANS_TM IS '거래시간';
COMMENT ON COLUMN SALES_TBL.MEMB_TY IS '회원구분';
COMMENT ON COLUMN SALES_TBL.MEMB_SER_NO IS '회원번호';
COMMENT ON COLUMN SALES_TBL.CANC_TY IS '취소구분';



-- 판매상품 테이블 O
CREATE TABLE SALES_PROD_TBL (
	SALES_DT        VARCHAR2(8)     NOT NULL, /* PK(FK) */
	SALES_SER_NO    VARCHAR2(4)     NOT NULL, /* PK(FK) */
	SER_NO          VARCHAR2(3)     NOT NULL, /* PK */
	PROD_CD         VARCHAR2(6)     NOT NULL,
    QTY             VARCHAR2(3)     NOT NULL,
    SALES_PR        VARCHAR2(13)    NOT NULL,
    VAT             VARCHAR2(13)    NOT NULL,
    SALES_AMT       VARCHAR2(13)    NOT NULL,
    SALE_AMT        VARCHAR2(13)    NOT NULL,
    TAX_TY          VARCHAR2(1)     NOT NULL, /* 과세 = 1, 비과세 = 2 */
    TRANS_TY        VARCHAR2(1)     NOT NULL, /* 일반 = 1, 무료 = 2, 반품(취소) = 3 */
    
    CONSTRAINT SALES_PROD_TBL_PK PRIMARY KEY(SALES_DT, SALES_SER_NO, SER_NO)
);

COMMENT ON TABLE SALES_PROD_TBL IS '판매상품';
COMMENT ON COLUMN SALES_PROD_TBL.SALES_DT IS '판매일자';
COMMENT ON COLUMN SALES_PROD_TBL.SALES_SER_NO IS '판매일련번호';
COMMENT ON COLUMN SALES_PROD_TBL.SER_NO IS '일련번호';
COMMENT ON COLUMN SALES_PROD_TBL.PROD_CD IS '상품코드';
COMMENT ON COLUMN SALES_PROD_TBL.QTY IS '수량';
COMMENT ON COLUMN SALES_PROD_TBL.SALES_PR IS '판매가격';
COMMENT ON COLUMN SALES_PROD_TBL.VAT IS '부가세';
COMMENT ON COLUMN SALES_PROD_TBL.SALES_AMT IS '판매금액';
COMMENT ON COLUMN SALES_PROD_TBL.SALE_AMT IS '할인금액';
COMMENT ON COLUMN SALES_PROD_TBL.TAX_TY IS '과세구분';
COMMENT ON COLUMN SALES_PROD_TBL.TRANS_TY IS '거래구분';



-- 판매결제 테이블 O
CREATE TABLE SALES_PAY_TBL (
	SALES_DT            VARCHAR2(8)     NOT NULL, /* PK(FK) */
	SALES_SER_NO        VARCHAR2(4)     NOT NULL, /* PK(FK) */
	SER_NO              VARCHAR2(3)     NOT NULL, /* PK(FK) */
	SALES_TY            VARCHAR2(1)     NOT NULL, /* PK */ /* 현금 = 1, 카드 = 2, (상품권 = 3, 포인트 = 4) */
    SALES_AMT           VARCHAR2(13)    NOT NULL,
    
    CONSTRAINT SALES_PAY_TBL_PK PRIMARY KEY(SALES_DT, SALES_SER_NO, SER_NO, SALES_TY)
);

COMMENT ON TABLE SALES_PAY_TBL IS '판매결제';
COMMENT ON COLUMN SALES_PAY_TBL.SALES_DT IS '판매일자';
COMMENT ON COLUMN SALES_PAY_TBL.SALES_SER_NO IS '판매일련번호';
COMMENT ON COLUMN SALES_PAY_TBL.SER_NO IS '일련번호';
COMMENT ON COLUMN SALES_PAY_TBL.SALES_TY IS '판매구분';
COMMENT ON COLUMN SALES_PAY_TBL.SALES_AMT IS '판매금액';



-- POS 테이블 생성 O
CREATE TABLE POS_TBL (
	TER_SER_NO      VARCHAR2(8)      NOT NULL   PRIMARY KEY,
	TER_NM          VARCHAR2(40)     NOT NULL,
	STORE_CD        VARCHAR2(3)      NOT NULL,
	VAN_NO          VARCHAR2(10)     NOT NULL
);

COMMENT ON TABLE POS_TBL IS 'POS';
COMMENT ON COLUMN POS_TBL.TER_SER_NO IS '단말기번호';
COMMENT ON COLUMN POS_TBL.TER_NM IS '단말기이름';
COMMENT ON COLUMN POS_TBL.STORE_CD IS '매장코드';
COMMENT ON COLUMN POS_TBL.VAN_NO IS 'VAN번호(신용카드 단말기)';



-- 매장정보 테이블 O
CREATE TABLE STORE_INFOR_TBL (
	STORE_CD        VARCHAR2(3)      NOT NULL   PRIMARY KEY,
	STORE_NM        VARCHAR2(40)     NOT NULL,
    STORE_AREA_CD   VARCHAR2(2)      NOT NULL, /* 서울 = 1, 경기 = 2 */
	REMARKS         VARCHAR2(100)    NOT NULL
);

COMMENT ON TABLE STORE_INFOR_TBL IS '매장정보';
COMMENT ON COLUMN STORE_INFOR_TBL.STORE_CD IS '매장코드';
COMMENT ON COLUMN STORE_INFOR_TBL.STORE_NM IS '매장이름';
COMMENT ON COLUMN STORE_INFOR_TBL.STORE_AREA_CD IS '매장지역코드';
COMMENT ON COLUMN STORE_INFOR_TBL.REMARKS IS '비고';
        
        

-- 시제금 테이블 O
CREATE TABLE VAULT_CASH_TBL (
	TER_SER_NO      VARCHAR2(8)     NOT NULL, /* PK */
	DEP_PAY_DT      VARCHAR2(8)     NOT NULL, /* PK */
	DEP_PAY_TM      VARCHAR2(8)     NOT NULL, /* PK */
    DEP_PAY_TY      VARCHAR2(1)     NOT NULL, /* 입금 = 1, 출금 = 2 */
    CONTENTS        VARCHAR2(40)    NOT NULL,
    AMT             VARCHAR2(13)    NOT NULL,
    
    CONSTRAINT VAULT_CASH_TBL_PK PRIMARY KEY(TER_SER_NO, DEP_PAY_DT, DEP_PAY_TM)
);

COMMENT ON TABLE VAULT_CASH_TBL IS '시제금';
COMMENT ON COLUMN VAULT_CASH_TBL.TER_SER_NO IS '단말기번호';
COMMENT ON COLUMN VAULT_CASH_TBL.DEP_PAY_DT IS '입출금일자';
COMMENT ON COLUMN VAULT_CASH_TBL.DEP_PAY_TM IS '입출금시간';
COMMENT ON COLUMN VAULT_CASH_TBL.DEP_PAY_TY IS '입출금구분';
COMMENT ON COLUMN VAULT_CASH_TBL.CONTENTS IS '내용';
COMMENT ON COLUMN VAULT_CASH_TBL.AMT IS '금액';



-- 회원 테이블 O
CREATE TABLE MEMB_TBL (
	MEMB_SER_NO     VARCHAR2(6)         NOT NULL    PRIMARY KEY,
	PERS_COP_TY     VARCHAR2(1)         NOT NULL,
	ID_NO           VARCHAR2(13),
    BUSI_NO         VARCHAR2(10),
    MEMB_NM         VARCHAR2(40)        NOT NULL,
    MEMB_ENG_NM     VARCHAR2(40)        NOT NULL,
    BIR_DAY         VARCHAR2(8),        /* 약식등록을 위한 NULL 허용 */
    MOB_PH_NO       VARCHAR2(12)        NOT NULL,
    PH_NO           VARCHAR2(12),
    POST_NO         VARCHAR2(5),        /* 약식등록을 위한 NULL 허용 */
    ADDR_1          VARCHAR2(100),      /* 약식등록을 위한 NULL 허용 */
    ADDR_2          VARCHAR2(100),      /* 약식등록을 위한 NULL 허용 */
    EMAIL           VARCHAR2(40),
    SECE_DT         VARCHAR2(8)
);

COMMENT ON TABLE MEMB_TBL IS '회원';
COMMENT ON COLUMN MEMB_TBL.MEMB_SER_NO IS '회원번호';
COMMENT ON COLUMN MEMB_TBL.PERS_COP_TY IS '개인법인구분';
COMMENT ON COLUMN MEMB_TBL.ID_NO IS '주민번호';
COMMENT ON COLUMN MEMB_TBL.BUSI_NO IS '사업자번호';
COMMENT ON COLUMN MEMB_TBL.MEMB_NM IS '회원성명';
COMMENT ON COLUMN MEMB_TBL.MEMB_ENG_NM IS '회원 영문명';
COMMENT ON COLUMN MEMB_TBL.BIR_DAY IS '생년월일';
COMMENT ON COLUMN MEMB_TBL.MOB_PH_NO IS '핸드폰번호';
COMMENT ON COLUMN MEMB_TBL.PH_NO IS '전화번호';
COMMENT ON COLUMN MEMB_TBL.POST_NO IS '우편번호';
COMMENT ON COLUMN MEMB_TBL.ADDR_1 IS '주소1';
COMMENT ON COLUMN MEMB_TBL.ADDR_2 IS '주소2';
COMMENT ON COLUMN MEMB_TBL.EMAIL IS '이메일주소';
COMMENT ON COLUMN MEMB_TBL.SECE_DT IS '탈퇴일자';



-- 상품 테이블 O
CREATE TABLE PROD_TBL (
	PROD_CD             VARCHAR2(6)     NOT NULL    PRIMARY KEY,
	PROD_CLS_CD         VARCHAR2(3)     NOT NULL,
	PROD_NM             VARCHAR2(40)    NOT NULL,
    PROD_ENG_NM         VARCHAR2(40)    NOT NULL,
    ORIG_NAT            VARCHAR2(20)    NOT NULL,
    PURC_PR             VARCHAR2(13)    NOT NULL,
    SELL_PR             VARCHAR2(13)    NOT NULL,
    BAR_CODE            VARCHAR2(20)    NOT NULL,
    CLIENT_NO           VARCHAR2(6)     NOT NULL,
    COLOR               VARCHAR2(20),
    PROD_SIZE           VARCHAR2(20),
    SALE_OR_NOT         VARCHAR2(1)     NOT NULL, /* 세일O = 1, 세일X = 0 */
    SALE_PR             VARCHAR2(13),
    TAXAT_TY            VARCHAR2(1)     NOT NULL, /* 과세 = 1, 비과세 = 2 */
    MEM_POINT           VARCHAR2(3)
);

COMMENT ON TABLE PROD_TBL IS '상품';
COMMENT ON COLUMN PROD_TBL.PROD_CD IS '상품코드';
COMMENT ON COLUMN PROD_TBL.PROD_CLS_CD IS '상품분류코드';
COMMENT ON COLUMN PROD_TBL.PROD_NM IS '상품명';
COMMENT ON COLUMN PROD_TBL.PROD_ENG_NM IS '상품영문명';
COMMENT ON COLUMN PROD_TBL.ORIG_NAT IS '원산지';
COMMENT ON COLUMN PROD_TBL.PURC_PR IS '구매원가';
COMMENT ON COLUMN PROD_TBL.SELL_PR IS '판매가';
COMMENT ON COLUMN PROD_TBL.BAR_CODE IS '바코드';
COMMENT ON COLUMN PROD_TBL.CLIENT_NO IS '거래처번호';
COMMENT ON COLUMN PROD_TBL.COLOR IS '색상';
COMMENT ON COLUMN PROD_TBL.PROD_SIZE IS '사이즈';
COMMENT ON COLUMN PROD_TBL.SALE_OR_NOT IS '세일여부';
COMMENT ON COLUMN PROD_TBL.SALE_PR IS '세일가격';
COMMENT ON COLUMN PROD_TBL.TAXAT_TY IS '과세구분';
COMMENT ON COLUMN PROD_TBL.MEM_POINT IS '회원포인트';



-- 상품분류 테이블 O
CREATE TABLE PROD_CLS_TBL (
	PROD_CLS_CD         VARCHAR2(3)     NOT NULL    PRIMARY KEY,
	PROD_CLS_NM         VARCHAR2(40)    NOT NULL,
	REMARKS             VARCHAR2(100)   NOT NULL
);

COMMENT ON TABLE PROD_CLS_TBL IS '상품분류';
COMMENT ON COLUMN PROD_CLS_TBL.PROD_CLS_CD IS '상품분류코드';
COMMENT ON COLUMN PROD_CLS_TBL.PROD_CLS_NM IS '상품분류명';
COMMENT ON COLUMN PROD_CLS_TBL.REMARKS IS '비고';



-- 거래처 테이블 O
CREATE TABLE CLIENT_TBL (
	CLIENT_NO       VARCHAR2(6)     NOT NULL    PRIMARY KEY,
	CLIENT_NM       VARCHAR2(40)    NOT NULL,
	BUSI_NO         VARCHAR2(10)    NOT NULL,
    PERS_COP_TY     VARCHAR2(1)     NOT NULL,
    ID_NO           VARCHAR2(13)    NOT NULL,
    REPRES_NM       VARCHAR2(40)    NOT NULL,
    PH_NO           VARCHAR2(12)    NOT NULL,
    POST_NO         VARCHAR2(5)     NOT NULL,
    ADDR            VARCHAR2(100)   NOT NULL
);

COMMENT ON TABLE CLIENT_TBL IS '거래처';
COMMENT ON COLUMN CLIENT_TBL.CLIENT_NO IS '거래처번호';
COMMENT ON COLUMN CLIENT_TBL.CLIENT_NM IS '거래처명';
COMMENT ON COLUMN CLIENT_TBL.BUSI_NO IS '사업자번호';
COMMENT ON COLUMN CLIENT_TBL.PERS_COP_TY IS '개인법인구분';
COMMENT ON COLUMN CLIENT_TBL.ID_NO IS '주민번호';
COMMENT ON COLUMN CLIENT_TBL.REPRES_NM IS '대표자성명';
COMMENT ON COLUMN CLIENT_TBL.PH_NO IS '전화번호';
COMMENT ON COLUMN CLIENT_TBL.POST_NO IS '우편번호';
COMMENT ON COLUMN CLIENT_TBL.ADDR IS '주소';



-- test data insert
-- 상품분류 TB insert
--SELECT * FROM PROD_CLS_TBL;
INSERT INTO PROD_CLS_TBL (PROD_CLS_CD, PROD_CLS_NM, REMARKS) VALUES ('001', '가공식품', '이미 한번 가공된 식품류(라면, 과자, 음료, 통조림 등등)');
INSERT INTO PROD_CLS_TBL (PROD_CLS_CD, PROD_CLS_NM, REMARKS) VALUES ('002', '신선식품', '야채, 과일, 육류, 어류 등등');
INSERT INTO PROD_CLS_TBL (PROD_CLS_CD, PROD_CLS_NM, REMARKS) VALUES ('003', '디지털/가전', '디지털/가전제품류');
INSERT INTO PROD_CLS_TBL (PROD_CLS_CD, PROD_CLS_NM, REMARKS) VALUES ('004', '의류', '상의, 하의, 신발, 모자 등등');
INSERT INTO PROD_CLS_TBL (PROD_CLS_CD, PROD_CLS_NM, REMARKS) VALUES ('005', '일상용품', '세면용품, 청소용품 등등');

-- 상품 TB insert
--SELECT * FROM PROD_TBL;
INSERT INTO PROD_TBL 
(PROD_CD, PROD_CLS_CD, PROD_NM, PROD_ENG_NM, ORIG_NAT, PURC_PR, SELL_PR, BAR_CODE, CLIENT_NO, COLOR, PROD_SIZE, SALE_OR_NOT, TAXAT_TY)
VALUES 
('1', '001', '신라면 600g', 'Shin Ramen 600g', '대한민국', '10000', '6000', '8801043014830', '1', '빨강', '600g', '0', '1');
INSERT INTO PROD_TBL 
(PROD_CD, PROD_CLS_CD, PROD_NM, PROD_ENG_NM, ORIG_NAT, PURC_PR, SELL_PR, BAR_CODE, CLIENT_NO, COLOR, PROD_SIZE, SALE_OR_NOT, TAXAT_TY)
VALUES 
('2', '002', '이베리코 갈비살 구리 300g', 'pig meat 300g', '스페인', '6000', '18000', '0430000402182', '2', '분홍', '300g', '0', '1');
INSERT INTO PROD_TBL 
(PROD_CD, PROD_CLS_CD, PROD_NM, PROD_ENG_NM, ORIG_NAT, PURC_PR, SELL_PR, BAR_CODE, CLIENT_NO, COLOR, PROD_SIZE, SALE_OR_NOT, TAXAT_TY)
VALUES 
('3', '003', '보조배터리 10000mAh', 'Battery 10000mAh', '중국', '8000', '13500', '8809774023930', '3', '보라', '10000mAh', '0', '1');
INSERT INTO PROD_TBL 
(PROD_CD, PROD_CLS_CD, PROD_NM, PROD_ENG_NM, ORIG_NAT, PURC_PR, SELL_PR, BAR_CODE, CLIENT_NO, COLOR, PROD_SIZE, SALE_OR_NOT, TAXAT_TY)
VALUES 
('4', '004', '수면바지', 'sleeping pants', '대한민국', '4000', '9900', '8808906559965', '4', '검정', 'L', '0', '1');
INSERT INTO PROD_TBL 
(PROD_CD, PROD_CLS_CD, PROD_NM, PROD_ENG_NM, ORIG_NAT, PURC_PR, SELL_PR, BAR_CODE, CLIENT_NO, COLOR, PROD_SIZE, SALE_OR_NOT, TAXAT_TY)
VALUES 
('5', '005', '민트 립밤', 'Lip balm', '미국', '7000', '11000', '041388000466', '5', '녹색', '4.25g', '0', '1');



--회원번호
--거래처번호
--상품코드
--판매번호
--단만기번호
--매장코드
